/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.nibbannews;

import javax.swing.JFrame;

/**
 *
 * @author Admin
 */
public class AccountMaster extends javax.swing.JFrame {

    /**
     * Creates new form AccountMaster
     */
    public AccountMaster() {
        initComponents();
        setExtendedState(JFrame.MAXIMIZED_BOTH);
    }
    
    public AccountMaster(String db_username, String db_empid){
        initComponents();
        userID.setText(db_empid);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem19 = new javax.swing.JMenuItem();
        jMenuItem20 = new javax.swing.JMenuItem();
        jMenuItem21 = new javax.swing.JMenuItem();
        jDialog1 = new javax.swing.JDialog();
        jPanel2 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        userID = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        voucher_menu = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        dashboard_menu = new javax.swing.JMenu();
        financialStatement_menu = new javax.swing.JMenu();
        trailBalance_menuItem = new javax.swing.JMenuItem();
        jMenuItem14 = new javax.swing.JMenuItem();
        jMenuItem15 = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenu14 = new javax.swing.JMenu();
        accountMaster_menu = new javax.swing.JMenu();
        jMenuItem17 = new javax.swing.JMenuItem();
        groupMaster_menuItem = new javax.swing.JMenuItem();
        primaryMaster_menuItem = new javax.swing.JMenuItem();
        jMenu16 = new javax.swing.JMenu();
        jMenuItem5 = new javax.swing.JMenuItem();
        jMenuItem18 = new javax.swing.JMenuItem();
        jMenuItem6 = new javax.swing.JMenuItem();
        jMenuItem8 = new javax.swing.JMenuItem();
        jMenu6 = new javax.swing.JMenu();
        jMenu19 = new javax.swing.JMenu();
        jMenuItem9 = new javax.swing.JMenuItem();
        jMenuItem10 = new javax.swing.JMenuItem();
        jMenu18 = new javax.swing.JMenu();
        jMenuItem7 = new javax.swing.JMenuItem();
        jMenuItem16 = new javax.swing.JMenuItem();
        jMenu20 = new javax.swing.JMenu();
        jMenuItem11 = new javax.swing.JMenuItem();
        jMenuItem12 = new javax.swing.JMenuItem();
        jMenuItem13 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();

        jMenuItem19.setText("jMenuItem19");

        jMenuItem20.setText("jMenuItem20");

        jMenuItem21.setText("jMenuItem21");

        javax.swing.GroupLayout jDialog1Layout = new javax.swing.GroupLayout(jDialog1.getContentPane());
        jDialog1.getContentPane().setLayout(jDialog1Layout);
        jDialog1Layout.setHorizontalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jDialog1Layout.setVerticalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("NMPL Account Master");

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setText("Hello");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(1400, 0, 41, 30));
        jPanel1.add(userID, new org.netbeans.lib.awtextra.AbsoluteConstraints(1450, 0, 72, 30));

        jButton1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButton1.setText("Logout");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1520, 0, -1, 30));

        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\Admin\\Downloads\\nibban2.png")); // NOI18N
        jLabel1.setOpaque(true);
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -20, 1610, 920));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jMenuBar1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        voucher_menu.setText("Voucher");

        jMenuItem1.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_N, java.awt.event.InputEvent.ALT_DOWN_MASK));
        jMenuItem1.setText("Add Entry");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        voucher_menu.add(jMenuItem1);

        jMenuBar1.add(voucher_menu);

        dashboard_menu.setText("Dashboard");
        dashboard_menu.addMenuKeyListener(new javax.swing.event.MenuKeyListener() {
            public void menuKeyPressed(javax.swing.event.MenuKeyEvent evt) {
                dashboard_menuMenuKeyPressed(evt);
            }
            public void menuKeyReleased(javax.swing.event.MenuKeyEvent evt) {
            }
            public void menuKeyTyped(javax.swing.event.MenuKeyEvent evt) {
            }
        });
        dashboard_menu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dashboard_menuActionPerformed(evt);
            }
        });
        jMenuBar1.add(dashboard_menu);

        financialStatement_menu.setText("Financial Statement");

        trailBalance_menuItem.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_T, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        trailBalance_menuItem.setText("Trail Balance");
        trailBalance_menuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                trailBalance_menuItemActionPerformed(evt);
            }
        });
        financialStatement_menu.add(trailBalance_menuItem);

        jMenuItem14.setText("Financial Notes");
        financialStatement_menu.add(jMenuItem14);

        jMenuItem15.setText("P&L Account");
        financialStatement_menu.add(jMenuItem15);

        jMenu4.setText("Balance sheet");

        jMenuItem2.setText("Horizontal Balance Sheet");
        jMenu4.add(jMenuItem2);

        jMenuItem3.setText("Vertical Balance Sheet");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenu4.add(jMenuItem3);

        financialStatement_menu.add(jMenu4);

        jMenuItem4.setText("Fix Assets");
        financialStatement_menu.add(jMenuItem4);

        jMenuBar1.add(financialStatement_menu);

        jMenu14.setText("Masters");

        accountMaster_menu.setText("Account Masters");
        accountMaster_menu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                accountMaster_menuActionPerformed(evt);
            }
        });

        jMenuItem17.setText("Ledger Master");
        jMenuItem17.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem17ActionPerformed(evt);
            }
        });
        accountMaster_menu.add(jMenuItem17);

        groupMaster_menuItem.setText("Group Master");
        groupMaster_menuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                groupMaster_menuItemActionPerformed(evt);
            }
        });
        accountMaster_menu.add(groupMaster_menuItem);

        primaryMaster_menuItem.setText("Primary Group");
        primaryMaster_menuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                primaryMaster_menuItemActionPerformed(evt);
            }
        });
        accountMaster_menu.add(primaryMaster_menuItem);

        jMenu14.add(accountMaster_menu);

        jMenu16.setText("Tax Masters");

        jMenuItem5.setText("GST Master");
        jMenuItem5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem5ActionPerformed(evt);
            }
        });
        jMenu16.add(jMenuItem5);

        jMenuItem18.setText("TDS Master");
        jMenuItem18.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem18ActionPerformed(evt);
            }
        });
        jMenu16.add(jMenuItem18);

        jMenu14.add(jMenu16);

        jMenuItem6.setText("Financial Year Master");
        jMenu14.add(jMenuItem6);

        jMenuItem8.setText("Assesment Year Master");
        jMenu14.add(jMenuItem8);

        jMenuBar1.add(jMenu14);

        jMenu6.setText("Reports");

        jMenu19.setText("Accounting Report");

        jMenuItem9.setText("Ledger Reports");
        jMenu19.add(jMenuItem9);

        jMenuItem10.setText("Group Reports");
        jMenu19.add(jMenuItem10);

        jMenu6.add(jMenu19);

        jMenu18.setText("Tax Report");

        jMenuItem7.setText("Direct Tax Reports");
        jMenu18.add(jMenuItem7);

        jMenuItem16.setText("Indirect Tax Reports");
        jMenu18.add(jMenuItem16);

        jMenu6.add(jMenu18);

        jMenu20.setText("Financial Report");

        jMenuItem11.setText("P&L Account Report");
        jMenu20.add(jMenuItem11);

        jMenuItem12.setText("Trial Balance Report");
        jMenu20.add(jMenuItem12);

        jMenuItem13.setText("Balance Sheet Report");
        jMenu20.add(jMenuItem13);

        jMenu6.add(jMenu20);

        jMenuBar1.add(jMenu6);

        jMenu2.setText("Bank Reconciliation Statement");
        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // TODO add your handling code here:
        new CreateVoucher().setVisible(true);
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void trailBalance_menuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_trailBalance_menuItemActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_trailBalance_menuItemActionPerformed

    private void groupMaster_menuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_groupMaster_menuItemActionPerformed
        // TODO add your handling code here:
        new GroupMaster().setVisible(true);
    }//GEN-LAST:event_groupMaster_menuItemActionPerformed

    private void accountMaster_menuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_accountMaster_menuActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_accountMaster_menuActionPerformed

    private void dashboard_menuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dashboard_menuActionPerformed
        // TODO add your handling code here:
        new AccountDashboard().setVisible(true);
    }//GEN-LAST:event_dashboard_menuActionPerformed

    private void dashboard_menuMenuKeyPressed(javax.swing.event.MenuKeyEvent evt) {//GEN-FIRST:event_dashboard_menuMenuKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_dashboard_menuMenuKeyPressed

    private void jMenuItem17ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem17ActionPerformed
        // TODO add your handling code here:
        LedgerMaster lm = new LedgerMaster();
        lm.setVisible(true);
    }//GEN-LAST:event_jMenuItem17ActionPerformed

    private void primaryMaster_menuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_primaryMaster_menuItemActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_primaryMaster_menuItemActionPerformed

    private void jMenuItem5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem5ActionPerformed
        // TODO add your handling code here:
        new GstMaster().setVisible(true);
    }//GEN-LAST:event_jMenuItem5ActionPerformed

    private void jMenuItem18ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem18ActionPerformed
        // TODO add your handling code here:
        new TdsMaster().setVisible(true);
    }//GEN-LAST:event_jMenuItem18ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        UserLogin ul = new UserLogin();
        ul.setVisible(true);
        dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AccountMaster.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AccountMaster.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AccountMaster.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AccountMaster.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AccountMaster().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu accountMaster_menu;
    private javax.swing.JMenu dashboard_menu;
    private javax.swing.JMenu financialStatement_menu;
    private javax.swing.JMenuItem groupMaster_menuItem;
    private javax.swing.JButton jButton1;
    private javax.swing.JDialog jDialog1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JMenu jMenu14;
    private javax.swing.JMenu jMenu16;
    private javax.swing.JMenu jMenu18;
    private javax.swing.JMenu jMenu19;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu20;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu6;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem10;
    private javax.swing.JMenuItem jMenuItem11;
    private javax.swing.JMenuItem jMenuItem12;
    private javax.swing.JMenuItem jMenuItem13;
    private javax.swing.JMenuItem jMenuItem14;
    private javax.swing.JMenuItem jMenuItem15;
    private javax.swing.JMenuItem jMenuItem16;
    private javax.swing.JMenuItem jMenuItem17;
    private javax.swing.JMenuItem jMenuItem18;
    private javax.swing.JMenuItem jMenuItem19;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem20;
    private javax.swing.JMenuItem jMenuItem21;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JMenuItem jMenuItem6;
    private javax.swing.JMenuItem jMenuItem7;
    private javax.swing.JMenuItem jMenuItem8;
    private javax.swing.JMenuItem jMenuItem9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JMenuItem primaryMaster_menuItem;
    private javax.swing.JMenuItem trailBalance_menuItem;
    private javax.swing.JLabel userID;
    private javax.swing.JMenu voucher_menu;
    // End of variables declaration//GEN-END:variables
}
