/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.nibbannews;

import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.List;
import java.awt.print.PageFormat;
import java.awt.print.Printable;
import java.awt.print.PrinterException;
import java.awt.print.PrinterJob;
import java.sql.Connection;
import java.sql.Date;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JTextField;

/**
 *
 * @author Admin
 */
public class CreateVoucher extends javax.swing.JFrame {

    /**
     * Creates new form CreateLedger
     */
    public CreateVoucher() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        txt_crLedgerCode = new javax.swing.JTextField();
        lbl_ledgerCrCode = new javax.swing.JLabel();
        lbl_ledgerCrName = new javax.swing.JLabel();
        lbl_ledgerCrAmt = new javax.swing.JLabel();
        txt_crLedgerName = new javax.swing.JTextField();
        txt_crAmt = new javax.swing.JTextField();
        lbl_ChequeNo = new javax.swing.JLabel();
        lbl_ChequeDate = new javax.swing.JLabel();
        txt_ChequeNo = new javax.swing.JTextField();
        chq_date = new com.toedter.calendar.JDateChooser();
        lbl_gstcode = new javax.swing.JLabel();
        lbl_cgstCode = new javax.swing.JLabel();
        lbl_sgstCode = new javax.swing.JLabel();
        lbl_igstCode = new javax.swing.JLabel();
        txt_gstcode = new javax.swing.JTextField();
        txt_cgstCode = new javax.swing.JTextField();
        txt_sgstCode = new javax.swing.JTextField();
        txt_igstCode = new javax.swing.JTextField();
        lbl_drawnon = new javax.swing.JLabel();
        txt_drawnon = new javax.swing.JTextField();
        btn_updateVoucher = new javax.swing.JButton();
        btn_cancel = new javax.swing.JButton();
        lbl_ledgerDrCode = new javax.swing.JLabel();
        lbl_ledgerDrName = new javax.swing.JLabel();
        lbl_ledgerDrAmt = new javax.swing.JLabel();
        txt_drLedgerCode = new javax.swing.JTextField();
        txt_drLedgerName = new javax.swing.JTextField();
        txt_drAmt = new javax.swing.JTextField();
        lbl_chequeBranch = new javax.swing.JLabel();
        txt_chequeBranch = new javax.swing.JTextField();
        lbl_tds = new javax.swing.JLabel();
        lbl_tdsCode = new javax.swing.JLabel();
        lbl_tdsRate = new javax.swing.JLabel();
        txt_tds = new javax.swing.JTextField();
        txt_tdsCode = new javax.swing.JTextField();
        txt_tdsRate = new javax.swing.JTextField();
        lbl_basicTdsAmt = new javax.swing.JLabel();
        lbl_surchargeTdsAmt = new javax.swing.JLabel();
        txt_basicTdsAmt = new javax.swing.JTextField();
        txt_surchargeTdsAmt = new javax.swing.JTextField();
        lbl_eduTdsAmt = new javax.swing.JLabel();
        txt_eduTdsAmt = new javax.swing.JTextField();
        lbl_branch = new javax.swing.JLabel();
        txt_branch = new javax.swing.JTextField();
        lbl_department = new javax.swing.JLabel();
        txt_department = new javax.swing.JTextField();
        lbl_segment = new javax.swing.JLabel();
        txt_segment = new javax.swing.JTextField();
        txt_product = new javax.swing.JTextField();
        lbl_product = new javax.swing.JLabel();
        lbl_narration = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txt_narration = new javax.swing.JTextArea();
        btn_findVoucher = new javax.swing.JButton();
        btn_createVoucher = new javax.swing.JButton();
        btn_deleteVoucher = new javax.swing.JButton();
        lbl_ledgerCrCode1 = new javax.swing.JLabel();
        txt_voucherCode = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        txt_receipt = new javax.swing.JTextArea();
        btn_printVoucher = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Expenses Vouche Entry");

        jPanel1.setBackground(new java.awt.Color(52, 51, 52));

        txt_crLedgerCode.setBackground(new java.awt.Color(52, 51, 52));
        txt_crLedgerCode.setForeground(new java.awt.Color(255, 255, 255));
        txt_crLedgerCode.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(255, 255, 255)));
        txt_crLedgerCode.addInputMethodListener(new java.awt.event.InputMethodListener() {
            public void caretPositionChanged(java.awt.event.InputMethodEvent evt) {
            }
            public void inputMethodTextChanged(java.awt.event.InputMethodEvent evt) {
                txt_crLedgerCodeInputMethodTextChanged(evt);
            }
        });
        txt_crLedgerCode.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_crLedgerCodeActionPerformed(evt);
            }
        });

        lbl_ledgerCrCode.setBackground(new java.awt.Color(255, 255, 255));
        lbl_ledgerCrCode.setForeground(new java.awt.Color(255, 255, 255));
        lbl_ledgerCrCode.setText("Ledger Code");

        lbl_ledgerCrName.setBackground(new java.awt.Color(255, 255, 255));
        lbl_ledgerCrName.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        lbl_ledgerCrName.setForeground(new java.awt.Color(255, 255, 255));
        lbl_ledgerCrName.setText("Ledger Name");

        lbl_ledgerCrAmt.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        lbl_ledgerCrAmt.setForeground(new java.awt.Color(255, 255, 255));
        lbl_ledgerCrAmt.setText("Amount");

        txt_crLedgerName.setBackground(new java.awt.Color(52, 51, 52));
        txt_crLedgerName.setForeground(new java.awt.Color(255, 255, 255));
        txt_crLedgerName.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(255, 255, 255)));

        txt_crAmt.setBackground(new java.awt.Color(52, 51, 52));
        txt_crAmt.setForeground(new java.awt.Color(255, 255, 255));
        txt_crAmt.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(255, 255, 255)));

        lbl_ChequeNo.setForeground(new java.awt.Color(255, 255, 255));
        lbl_ChequeNo.setText("Cheque No");

        lbl_ChequeDate.setForeground(new java.awt.Color(255, 255, 255));
        lbl_ChequeDate.setText("Cheque Date");

        txt_ChequeNo.setBackground(new java.awt.Color(52, 51, 52));
        txt_ChequeNo.setForeground(new java.awt.Color(255, 255, 255));
        txt_ChequeNo.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(255, 255, 255)));

        chq_date.setBackground(new java.awt.Color(52, 51, 52));
        chq_date.setDateFormatString("dd/MM/ y");

        lbl_gstcode.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        lbl_gstcode.setForeground(new java.awt.Color(255, 255, 255));
        lbl_gstcode.setText("GST code(%)");

        lbl_cgstCode.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        lbl_cgstCode.setForeground(new java.awt.Color(255, 255, 255));
        lbl_cgstCode.setText("CGST code");

        lbl_sgstCode.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        lbl_sgstCode.setForeground(new java.awt.Color(255, 255, 255));
        lbl_sgstCode.setText("SGST code");

        lbl_igstCode.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        lbl_igstCode.setForeground(new java.awt.Color(255, 255, 255));
        lbl_igstCode.setText("IGST code");

        txt_gstcode.setBackground(new java.awt.Color(52, 51, 52));
        txt_gstcode.setForeground(new java.awt.Color(255, 255, 255));
        txt_gstcode.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(255, 255, 255)));

        txt_cgstCode.setBackground(new java.awt.Color(52, 51, 52));
        txt_cgstCode.setForeground(new java.awt.Color(255, 255, 255));
        txt_cgstCode.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(255, 255, 255)));

        txt_sgstCode.setBackground(new java.awt.Color(52, 51, 52));
        txt_sgstCode.setForeground(new java.awt.Color(255, 255, 255));
        txt_sgstCode.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(255, 255, 255)));

        txt_igstCode.setBackground(new java.awt.Color(52, 51, 52));
        txt_igstCode.setForeground(new java.awt.Color(255, 255, 255));
        txt_igstCode.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(255, 255, 255)));

        lbl_drawnon.setForeground(new java.awt.Color(255, 255, 255));
        lbl_drawnon.setText("Drawn on");

        txt_drawnon.setBackground(new java.awt.Color(52, 51, 52));
        txt_drawnon.setForeground(new java.awt.Color(255, 255, 255));
        txt_drawnon.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(255, 255, 255)));

        btn_updateVoucher.setBackground(new java.awt.Color(52, 51, 52));
        btn_updateVoucher.setForeground(new java.awt.Color(255, 255, 255));
        btn_updateVoucher.setText("Update Entry");
        btn_updateVoucher.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_updateVoucher.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_updateVoucherActionPerformed(evt);
            }
        });

        btn_cancel.setBackground(new java.awt.Color(52, 51, 52));
        btn_cancel.setForeground(new java.awt.Color(255, 255, 255));
        btn_cancel.setText("Cancel");
        btn_cancel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_cancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_cancelActionPerformed(evt);
            }
        });

        lbl_ledgerDrCode.setForeground(new java.awt.Color(255, 255, 255));
        lbl_ledgerDrCode.setText("Ledger Code");

        lbl_ledgerDrName.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        lbl_ledgerDrName.setForeground(new java.awt.Color(255, 255, 255));
        lbl_ledgerDrName.setText("Ledger Name");

        lbl_ledgerDrAmt.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        lbl_ledgerDrAmt.setForeground(new java.awt.Color(255, 255, 255));
        lbl_ledgerDrAmt.setText("Amount");

        txt_drLedgerCode.setBackground(new java.awt.Color(52, 51, 52));
        txt_drLedgerCode.setForeground(new java.awt.Color(255, 255, 255));
        txt_drLedgerCode.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(255, 255, 255)));

        txt_drLedgerName.setBackground(new java.awt.Color(52, 51, 52));
        txt_drLedgerName.setForeground(new java.awt.Color(255, 255, 255));
        txt_drLedgerName.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(255, 255, 255)));

        txt_drAmt.setBackground(new java.awt.Color(52, 51, 52));
        txt_drAmt.setForeground(new java.awt.Color(255, 255, 255));
        txt_drAmt.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(255, 255, 255)));
        txt_drAmt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_drAmtActionPerformed(evt);
            }
        });

        lbl_chequeBranch.setForeground(new java.awt.Color(255, 255, 255));
        lbl_chequeBranch.setText("Branch");

        txt_chequeBranch.setBackground(new java.awt.Color(52, 51, 52));
        txt_chequeBranch.setForeground(new java.awt.Color(255, 255, 255));
        txt_chequeBranch.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(255, 255, 255)));
        txt_chequeBranch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_chequeBranchActionPerformed(evt);
            }
        });

        lbl_tds.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        lbl_tds.setForeground(new java.awt.Color(255, 255, 255));
        lbl_tds.setText("TDS");

        lbl_tdsCode.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        lbl_tdsCode.setForeground(new java.awt.Color(255, 255, 255));
        lbl_tdsCode.setText("TDS code");

        lbl_tdsRate.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        lbl_tdsRate.setForeground(new java.awt.Color(255, 255, 255));
        lbl_tdsRate.setText("TDS rate");

        txt_tds.setBackground(new java.awt.Color(52, 51, 52));
        txt_tds.setForeground(new java.awt.Color(255, 255, 255));
        txt_tds.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(255, 255, 255)));

        txt_tdsCode.setBackground(new java.awt.Color(52, 51, 52));
        txt_tdsCode.setForeground(new java.awt.Color(255, 255, 255));
        txt_tdsCode.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(255, 255, 255)));

        txt_tdsRate.setBackground(new java.awt.Color(52, 51, 52));
        txt_tdsRate.setForeground(new java.awt.Color(255, 255, 255));
        txt_tdsRate.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(255, 255, 255)));

        lbl_basicTdsAmt.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        lbl_basicTdsAmt.setForeground(new java.awt.Color(255, 255, 255));
        lbl_basicTdsAmt.setText("Basic TDS Amt");

        lbl_surchargeTdsAmt.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        lbl_surchargeTdsAmt.setForeground(new java.awt.Color(255, 255, 255));
        lbl_surchargeTdsAmt.setText("Surcharge TDS Amt");

        txt_basicTdsAmt.setBackground(new java.awt.Color(52, 51, 52));
        txt_basicTdsAmt.setForeground(new java.awt.Color(255, 255, 255));
        txt_basicTdsAmt.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(255, 255, 255)));

        txt_surchargeTdsAmt.setBackground(new java.awt.Color(52, 51, 52));
        txt_surchargeTdsAmt.setForeground(new java.awt.Color(255, 255, 255));
        txt_surchargeTdsAmt.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(255, 255, 255)));

        lbl_eduTdsAmt.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        lbl_eduTdsAmt.setForeground(new java.awt.Color(255, 255, 255));
        lbl_eduTdsAmt.setText("Education Cess TDS Amt/Secondary & Higher Education Cess TDS Amt\t\t\t\t ");

        txt_eduTdsAmt.setBackground(new java.awt.Color(52, 51, 52));
        txt_eduTdsAmt.setForeground(new java.awt.Color(255, 255, 255));
        txt_eduTdsAmt.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(255, 255, 255)));

        lbl_branch.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        lbl_branch.setForeground(new java.awt.Color(255, 255, 255));
        lbl_branch.setText("Branch code");

        txt_branch.setBackground(new java.awt.Color(52, 51, 52));
        txt_branch.setForeground(new java.awt.Color(255, 255, 255));
        txt_branch.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(255, 255, 255)));

        lbl_department.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        lbl_department.setForeground(new java.awt.Color(255, 255, 255));
        lbl_department.setText("Department code");

        txt_department.setBackground(new java.awt.Color(52, 51, 52));
        txt_department.setForeground(new java.awt.Color(255, 255, 255));
        txt_department.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(255, 255, 255)));

        lbl_segment.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        lbl_segment.setForeground(new java.awt.Color(255, 255, 255));
        lbl_segment.setText("Segment code");

        txt_segment.setBackground(new java.awt.Color(52, 51, 52));
        txt_segment.setForeground(new java.awt.Color(255, 255, 255));
        txt_segment.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(255, 255, 255)));

        txt_product.setBackground(new java.awt.Color(52, 51, 52));
        txt_product.setForeground(new java.awt.Color(255, 255, 255));
        txt_product.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(255, 255, 255)));

        lbl_product.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        lbl_product.setForeground(new java.awt.Color(255, 255, 255));
        lbl_product.setText("Product code");

        lbl_narration.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        lbl_narration.setForeground(new java.awt.Color(255, 255, 255));
        lbl_narration.setText("Narration");

        txt_narration.setBackground(new java.awt.Color(52, 51, 52));
        txt_narration.setColumns(20);
        txt_narration.setForeground(new java.awt.Color(255, 255, 255));
        txt_narration.setRows(5);
        txt_narration.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(255, 255, 255)));
        txt_narration.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        jScrollPane1.setViewportView(txt_narration);

        btn_findVoucher.setBackground(new java.awt.Color(52, 51, 52));
        btn_findVoucher.setForeground(new java.awt.Color(255, 255, 255));
        btn_findVoucher.setText("Find Entry");
        btn_findVoucher.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_findVoucher.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_findVoucherActionPerformed(evt);
            }
        });

        btn_createVoucher.setBackground(new java.awt.Color(52, 51, 52));
        btn_createVoucher.setForeground(new java.awt.Color(255, 255, 255));
        btn_createVoucher.setText("Add Entry");
        btn_createVoucher.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_createVoucher.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_createVoucherActionPerformed(evt);
            }
        });

        btn_deleteVoucher.setBackground(new java.awt.Color(52, 51, 52));
        btn_deleteVoucher.setForeground(new java.awt.Color(255, 255, 255));
        btn_deleteVoucher.setText("Delete Entry");
        btn_deleteVoucher.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_deleteVoucher.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_deleteVoucherActionPerformed(evt);
            }
        });

        lbl_ledgerCrCode1.setBackground(new java.awt.Color(255, 255, 255));
        lbl_ledgerCrCode1.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        lbl_ledgerCrCode1.setForeground(new java.awt.Color(255, 255, 255));
        lbl_ledgerCrCode1.setText("Voucher Entry");

        txt_voucherCode.setBackground(new java.awt.Color(52, 51, 52));
        txt_voucherCode.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        txt_voucherCode.setForeground(new java.awt.Color(255, 255, 51));
        txt_voucherCode.setBorder(null);
        txt_voucherCode.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_voucherCodeActionPerformed(evt);
            }
        });

        txt_receipt.setEditable(false);
        txt_receipt.setColumns(20);
        txt_receipt.setRows(5);
        jScrollPane2.setViewportView(txt_receipt);

        btn_printVoucher.setBackground(new java.awt.Color(52, 51, 52));
        btn_printVoucher.setForeground(new java.awt.Color(255, 255, 255));
        btn_printVoucher.setText("Print Entry");
        btn_printVoucher.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_printVoucher.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_printVoucherActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(lbl_ledgerCrCode1)
                            .addGap(18, 18, 18)
                            .addComponent(txt_voucherCode, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(txt_gstcode)
                                .addComponent(lbl_gstcode, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(lbl_tds, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(txt_tds)
                                .addComponent(lbl_basicTdsAmt, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(txt_basicTdsAmt, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addGap(36, 36, 36)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                .addComponent(lbl_cgstCode)
                                                .addComponent(txt_cgstCode, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(lbl_tdsCode)
                                                .addComponent(txt_tdsCode, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGap(40, 40, 40)
                                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                .addComponent(lbl_sgstCode, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(txt_sgstCode, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(lbl_tdsRate, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(txt_tdsRate, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGap(34, 34, 34)
                                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(lbl_igstCode, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(txt_igstCode, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(lbl_surchargeTdsAmt)
                                                .addComponent(txt_surchargeTdsAmt, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGap(31, 31, 31)
                                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                .addComponent(lbl_eduTdsAmt, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(txt_eduTdsAmt, javax.swing.GroupLayout.PREFERRED_SIZE, 388, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addGap(155, 155, 155)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(lbl_segment, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(txt_segment, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGap(36, 36, 36)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(lbl_product, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(txt_product, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(lbl_narration, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(lbl_branch, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(txt_branch, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(34, 34, 34)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(lbl_department, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txt_department)))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(txt_ChequeNo, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(lbl_ChequeNo, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(24, 24, 24)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(lbl_ChequeDate, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(chq_date, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(27, 27, 27)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(lbl_drawnon, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txt_drawnon, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(28, 28, 28)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(lbl_chequeBranch, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txt_chequeBranch, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(lbl_ledgerDrCode)
                                .addComponent(lbl_ledgerCrCode)
                                .addComponent(txt_crLedgerCode, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addGap(21, 21, 21)
                                    .addComponent(lbl_ledgerCrName))
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addGap(18, 18, 18)
                                    .addComponent(txt_crLedgerName, javax.swing.GroupLayout.PREFERRED_SIZE, 354, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGap(18, 18, 18)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(txt_crAmt, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(lbl_ledgerCrAmt, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txt_drAmt, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(lbl_ledgerDrAmt, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(txt_drLedgerCode, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(24, 24, 24)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(lbl_ledgerDrName)
                                .addComponent(txt_drLedgerName, javax.swing.GroupLayout.PREFERRED_SIZE, 351, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 719, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btn_createVoucher)
                        .addGap(18, 18, 18)
                        .addComponent(btn_findVoucher)
                        .addGap(18, 18, 18)
                        .addComponent(btn_updateVoucher)
                        .addGap(18, 18, 18)
                        .addComponent(btn_deleteVoucher, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btn_printVoucher)
                        .addGap(18, 18, 18)
                        .addComponent(btn_cancel)
                        .addGap(59, 59, 59)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 545, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_ledgerCrCode1)
                    .addComponent(txt_voucherCode, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_ledgerCrCode, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lbl_ledgerCrName)
                    .addComponent(lbl_ledgerCrAmt, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_crLedgerName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_crAmt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_crLedgerCode, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_ledgerDrCode, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lbl_ledgerDrName)
                    .addComponent(lbl_ledgerDrAmt, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_drLedgerCode, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_drLedgerName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_drAmt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_ChequeNo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lbl_ChequeDate, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lbl_drawnon, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lbl_chequeBranch, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txt_ChequeNo)
                    .addComponent(chq_date, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txt_drawnon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txt_chequeBranch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(lbl_gstcode)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txt_gstcode, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(lbl_cgstCode)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txt_cgstCode, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(lbl_igstCode)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addComponent(txt_igstCode, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(lbl_sgstCode)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txt_sgstCode, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(lbl_tds)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txt_tds, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(lbl_tdsCode)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txt_tdsCode, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(lbl_tdsRate)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txt_tdsRate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(lbl_surchargeTdsAmt)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txt_surchargeTdsAmt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(12, 12, 12))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(lbl_basicTdsAmt, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txt_basicTdsAmt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(lbl_branch)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txt_branch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(lbl_department)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txt_department, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(lbl_segment)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(txt_segment, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                    .addComponent(lbl_product)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(txt_product, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lbl_narration)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                            .addComponent(lbl_eduTdsAmt)
                            .addGap(23, 23, 23))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGap(24, 24, 24)
                            .addComponent(txt_eduTdsAmt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_updateVoucher, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_findVoucher, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_deleteVoucher, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_createVoucher, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_printVoucher, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_cancel, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(48, 48, 48))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 1294, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btn_cancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_cancelActionPerformed
        // TODO add your handling code here:
//        new AccountMaster().setVisible(true);
        dispose();
    }//GEN-LAST:event_btn_cancelActionPerformed

    private void txt_drAmtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_drAmtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_drAmtActionPerformed

    private void txt_crLedgerCodeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_crLedgerCodeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_crLedgerCodeActionPerformed

    private void btn_createVoucherActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_createVoucherActionPerformed
        // TODO add your handling code here:
        String ledgerCodeCr = txt_crLedgerCode.getText();
        String ledgerNameCr = txt_crLedgerName.getText();
        String crAmount = txt_crAmt.getText();
        String ledgerCodeDr = txt_drLedgerCode.getText();
        String ledgerNameDr = txt_drLedgerName.getText();
        String drAmount = txt_crAmt.getText();
        String chqNo = txt_ChequeNo.getText();
            java.util.Date chqdate= chq_date.getDate();
            chqdate.getTime();
            SimpleDateFormat oDateFormat = new SimpleDateFormat("dd/MM/yyyy");
        String ChqDate = oDateFormat.format(chqdate.getTime());
        String drawnOn = txt_drawnon.getText();
        String chqBranch = txt_chequeBranch.getText();
        String gstCode = txt_gstcode.getText();
        String cgstCode = txt_cgstCode.getText();
        String sgstCode = txt_sgstCode.getText();
        String igstCode = txt_igstCode.getText();
        String tds = txt_tds.getText();
        String tdsCode = txt_tdsCode.getText();
        String tdsRate = txt_tdsRate.getText();
        String basicTdsAmt = txt_basicTdsAmt.getText();
        String surchargeTdsAmt = txt_surchargeTdsAmt.getText();
        String educationTdsAmt = txt_eduTdsAmt.getText();
        String branch = txt_branch.getText();
        String department = txt_department.getText();
        String segment = txt_segment.getText();
        String product = txt_product.getText();
        String narration = txt_narration.getText();
        if(ledgerCodeCr.equals("") || ledgerNameCr.equals("") || crAmount.equals("") || ledgerCodeDr.equals("") || ledgerNameDr.equals("") || 
                drAmount.equals("") || chqNo.equals("") || chqdate.equals("") || drawnOn.equals("") || chqBranch.equals("") || gstCode.equals("") ||
                cgstCode.equals("") || sgstCode.equals("") || igstCode.equals("") || tds.equals("") || tdsCode.equals("") || tdsRate.equals("") ||
                basicTdsAmt.equals("") || surchargeTdsAmt.equals("") || educationTdsAmt.equals("") || branch.equals("") || department.equals("") ||
                segment.equals("") || product.equals("") || narration.equals(""))
        {
            JOptionPane.showMessageDialog(rootPane, "All feilds are required");
        }
        else{
            try {
                DBConnection dbc = new DBConnection();
                Connection con = dbc.dbconnect();
                String queryCheck = "select * from voucher where ledgerCodeCr=?";
                PreparedStatement stmt = con.prepareStatement(queryCheck);
                stmt.setString(1, txt_crLedgerCode.getText());
                final ResultSet rs = stmt.executeQuery();
                // if this ID already exists, we quit
                if(rs.next()) {
                    con.close();
                    JOptionPane.showMessageDialog(this, "User already exit");
                    return;
                }else{
                String str = "insert into voucher values(?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)";
                stmt = con.prepareStatement(str);
                stmt.setString(1, txt_crLedgerCode.getText());
                stmt.setString(2, txt_crLedgerName.getText());
                stmt.setString(3, txt_crAmt.getText());
                stmt.setString(4, txt_drLedgerCode.getText());
                stmt.setString(5, txt_drLedgerName.getText());
                stmt.setString(6, txt_drAmt.getText());
                stmt.setString(7, txt_ChequeNo.getText());
                stmt.setString(8, ChqDate);
                stmt.setString(9, txt_drawnon.getText());
                stmt.setString(10, txt_chequeBranch.getText());
                stmt.setString(11, txt_gstcode.getText());
                stmt.setString(12, txt_cgstCode.getText());
                stmt.setString(13, txt_sgstCode.getText());
                stmt.setString(14, txt_igstCode.getText());
                stmt.setString(15, txt_tds.getText());
                stmt.setString(16, txt_tdsCode.getText());
                stmt.setString(17, txt_tdsRate.getText());
                stmt.setString(18, txt_basicTdsAmt.getText());
                stmt.setString(19, txt_surchargeTdsAmt.getText());
                stmt.setString(20, txt_eduTdsAmt.getText());
                stmt.setString(21, txt_branch.getText());
                stmt.setString(22, txt_department.getText());
                stmt.setString(23, txt_segment.getText());
                stmt.setString(24, txt_product.getText());
                stmt.setString(25, txt_narration.getText());
                stmt.executeUpdate();
                    JOptionPane.showMessageDialog(this, "Voucher Generated Successfully.");
                }
                    
//                    txt_receipt.setText("**********************************************************************************************************\n");
//                    txt_receipt.setText(txt_receipt.getText()+"\t\t\s\s Voucher Receipt \n");
//                    txt_receipt.setText(txt_receipt.getText()+"**********************************************************************************************************\n");
//                   
//                    txt_receipt.setText(txt_receipt.getText()+"\s\sLedger Code(cr) :"+txt_crLedgerCode.getText()+"\n");
//                    txt_receipt.setText(txt_receipt.getText()+"\s\sName Code(cr) :"+txt_CrLedgerName.getText()+"\n");
//                    txt_receipt.setText(txt_receipt.getText()+"\s\sAmount(cr) :"+txt_CrAmt.getText()+"\n");
//                    txt_receipt.setText(txt_receipt.getText()+"\s\sLedger Code(dr) :"+txt_drLedgerCode.getText()+"\n");
//                    txt_receipt.setText(txt_receipt.getText()+"\s\sLedger Name(dr) :"+txt_DrLedgerName.getText()+"\n");
//                    txt_receipt.setText(txt_receipt.getText()+"\s\sAmount :"+txt_DrAmt.getText()+"\n");
//                    txt_receipt.setText(txt_receipt.getText()+"\s\sCheque No. :"+txt_ChequeNo.getText()+"\n");
//                    txt_receipt.setText(txt_receipt.getText()+"\s\sDrawn on :"+txt_drawnon.getText()+"\n");
//                    txt_receipt.setText(txt_receipt.getText()+"\s\sBranch :"+txt_chequeBranch.getText()+"\n");
//                    txt_receipt.setText(txt_receipt.getText()+"\s\sGST Code :"+txt_gstcode.getText()+"\n");
//                    txt_receipt.setText(txt_receipt.getText()+"\s\sCGST Code :"+txt_cgstCode.getText()+"\n");
//                    txt_receipt.setText(txt_receipt.getText()+"\s\sSGST Code :"+txt_sgstCode.getText()+"\n");
//                    txt_receipt.setText(txt_receipt.getText()+"\s\sIGST Code :"+txt_igstCode.getText()+"\n");
//                    txt_receipt.setText(txt_receipt.getText()+"\s\sTDS :"+txt_tds.getText()+"\n");
//                    txt_receipt.setText(txt_receipt.getText()+"\s\sTDS Code :"+txt_tdsCode.getText()+"\n");
//                    txt_receipt.setText(txt_receipt.getText()+"\s\sTDS rate :"+txt_tdsRate.getText()+"\n");
//                    txt_receipt.setText(txt_receipt.getText()+"\s\sBasic TDS amt :"+txt_basicTdsAmt.getText()+"\n");
//                    txt_receipt.setText(txt_receipt.getText()+"\s\sSurcharge TDS amt :"+txt_surchargeTdsAmt.getText()+"\n");
//                    txt_receipt.setText(txt_receipt.getText()+"\s\sEdu TDS amt :"+txt_eduTdsAmt.getText()+"\n");
//                    txt_receipt.setText(txt_receipt.getText()+"\s\sBranch :"+txt_branch.getText()+"\n");
//                    txt_receipt.setText(txt_receipt.getText()+"\s\sDepartment :"+txt_department.getText()+"\n");
//                    txt_receipt.setText(txt_receipt.getText()+"\s\sSegment :"+txt_segment.getText()+"\n");
//                    txt_receipt.setText(txt_receipt.getText()+"\s\sProduct :"+txt_product.getText()+"\n");
//                    txt_receipt.setText(txt_receipt.getText()+"\s\sNarration :"+txt_narration.getText()+"\n");

                      
                    
                        txt_crLedgerCode.setText("");
                        txt_crLedgerName.setText("");
                        txt_crAmt.setText("");
                        txt_drLedgerCode.setText("");
                        txt_drLedgerName.setText("");
                        txt_drAmt.setText("");
                        txt_ChequeNo.setText("");
                        chq_date.setCalendar(null);
                        txt_drawnon.setText("");
                        txt_chequeBranch.setText("");
                        txt_gstcode.setText("");
                        txt_cgstCode.setText("");
                        txt_sgstCode.setText("");
                        txt_igstCode.setText("");
                        txt_tds.setText("");
                        txt_tdsCode.setText("");
                        txt_tdsRate.setText("");
                        txt_basicTdsAmt.setText("");
                        txt_surchargeTdsAmt.setText("");
                        txt_eduTdsAmt.setText("");
                        txt_branch.setText("");
                        txt_department.setText("");
                        txt_segment.setText("");
                        txt_product.setText("");
                        txt_narration.setText("");
                } 
                catch (SQLException ex) {
                    Logger.getLogger(CreateVoucher.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_btn_createVoucherActionPerformed

    private void txt_voucherCodeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_voucherCodeActionPerformed
            // TODO add your handling code here:
            
       
    }//GEN-LAST:event_txt_voucherCodeActionPerformed

    private void btn_findVoucherActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_findVoucherActionPerformed
        // TODO add your handling code here:
        String ledgerCodeCr = txt_crLedgerCode.getText();
        if(ledgerCodeCr.equals("")){
            JOptionPane.showMessageDialog(rootPane, "Enter Voucher code to search the voucher");
        }
        else{
        try {
            DBConnection dbc = new DBConnection();
            Connection con = dbc.dbconnect();
            String str = "select * from voucher where ledgerCodeCr=?";
            PreparedStatement stmt = con.prepareStatement(str);
            stmt.setString(1, txt_crLedgerCode.getText());
            ResultSet rs =  stmt.executeQuery();
            if(rs.next()){
                txt_crLedgerName.setText(rs.getString("ledgerNameCr"));
                txt_crAmt.setText(rs.getString("amountCr"));
                txt_drLedgerCode.setText(rs.getString("ledgerCodeDr"));
                txt_drLedgerName.setText(rs.getString("ledgerNameDr"));
                txt_drAmt.setText(rs.getString("amountDr"));
                txt_ChequeNo.setText(rs.getString("chequeNo"));
                    String date = rs.getString("chequeDate");
                    java.util.Date date1=new SimpleDateFormat("dd/MM/yyyy").parse(date);
                    chq_date.setDate(date1);
                txt_drawnon.setText(rs.getString("drawnOn"));
                txt_chequeBranch.setText(rs.getString("chqBranch"));
                txt_gstcode.setText(rs.getString("gstCode"));
                txt_cgstCode.setText(rs.getString("cgstCode"));
                txt_sgstCode.setText(rs.getString("sgstCode"));
                txt_igstCode.setText(rs.getString("igstCode"));
                txt_tds.setText(rs.getString("tds"));
                txt_tdsCode.setText(rs.getString("tdsCode"));
                txt_tdsRate.setText(rs.getString("tdsRate"));
                txt_basicTdsAmt.setText(rs.getString("basicTdsAmt"));
                txt_surchargeTdsAmt.setText(rs.getString("surchargeTdsAmt"));
                txt_eduTdsAmt.setText(rs.getString("educationTdsAmt"));
                txt_branch.setText(rs.getString("branch"));
                txt_department.setText(rs.getString("department"));
                txt_segment.setText(rs.getString("segment"));
                txt_product.setText(rs.getString("product"));
                txt_narration.setText(rs.getString("narration"));
            }
            else{
                JOptionPane.showMessageDialog(this, "NO Data found!");
            }
        } catch (SQLException ex) {
            Logger.getLogger(CreateVoucher.class.getName()).log(Level.SEVERE, null, ex);
        }   catch (ParseException ex) {
                Logger.getLogger(CreateVoucher.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_btn_findVoucherActionPerformed

    private void btn_updateVoucherActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_updateVoucherActionPerformed
        // TODO add your handling code here:
        String ledgerCodeCr = txt_crLedgerCode.getText();
        String ledgerNameCr = txt_crLedgerName.getText();
        String crAmount = txt_crAmt.getText();
        String ledgerCodeDr = txt_drLedgerCode.getText();
        String ledgerNameDr = txt_drLedgerName.getText();
        String drAmount = txt_crAmt.getText();
        String chqNo = txt_ChequeNo.getText();
            java.util.Date chqdate= chq_date.getDate();
            chqdate.getTime();
            SimpleDateFormat oDateFormat = new SimpleDateFormat("dd/MM/yyyy");
        String ChqDate = oDateFormat.format(chqdate.getTime());
        String drawnOn = txt_drawnon.getText();
        String chqBranch = txt_chequeBranch.getText();
        String gstCode = txt_gstcode.getText();
        String cgstCode = txt_cgstCode.getText();
        String sgstCode = txt_sgstCode.getText();
        String igstCode = txt_igstCode.getText();
        String tds = txt_tds.getText();
        String tdsCode = txt_tdsCode.getText();
        String tdsRate = txt_tdsRate.getText();
        String basicTdsAmt = txt_basicTdsAmt.getText();
        String surchargeTdsAmt = txt_surchargeTdsAmt.getText();
        String educationTdsAmt = txt_eduTdsAmt.getText();
        String branch = txt_branch.getText();
        String department = txt_department.getText();
        String segment = txt_segment.getText();
        String product = txt_product.getText();
        String narration = txt_narration.getText();
        if(ledgerCodeCr.equals("") || ledgerNameCr.equals("") || crAmount.equals("") || ledgerCodeDr.equals("") || ledgerNameDr.equals("") || 
                drAmount.equals("") || chqNo.equals("") || chqdate.equals("") || drawnOn.equals("") || chqBranch.equals("") || gstCode.equals("") ||
                cgstCode.equals("") || sgstCode.equals("") || igstCode.equals("") || tds.equals("") || tdsCode.equals("") || tdsRate.equals("") ||
                basicTdsAmt.equals("") || surchargeTdsAmt.equals("") || educationTdsAmt.equals("") || branch.equals("") || department.equals("") ||
                segment.equals("") || product.equals("") || narration.equals(""))
        {
            JOptionPane.showMessageDialog(rootPane, "No Data Found");
        }
        else{
            try {
                DBConnection dbc = new DBConnection();
                Connection con = dbc.dbconnect();
                String str = "Update voucher set ledgerNameCr='"+txt_crLedgerName.getText()+"',"
                        + "amountCr='"+txt_crAmt.getText()+"',"
                        + "ledgerCodeDr='"+txt_drLedgerCode.getText()+"',"
                        + "ledgerNameDr='"+txt_drLedgerName.getText()+"',"
                        + "amountDr='"+txt_drAmt.getText()+"',"
                        + "chequeNo='"+txt_ChequeNo.getText()+"',"
                        + "chequeDate='"+ChqDate+"',"
                        + "drawnOn='"+txt_drawnon.getText()+"',"
                        + "chqBranch='"+txt_chequeBranch.getText()+"',"
                        + "gstCode='"+txt_gstcode.getText()+"',"
                        + "cgstCode='"+txt_cgstCode.getText()+"',"
                        + "sgstCode='"+txt_sgstCode.getText()+"',"
                        + "igstCode='"+txt_igstCode.getText()+"',"
                        + "tds='"+txt_tds.getText()+"',"
                        + "tdsCode='"+txt_tdsCode.getText()+"',"
                        + "tdsRate='"+txt_tdsRate.getText()+"',"
                        + "basicTdsAmt='"+txt_basicTdsAmt.getText()+"',"
                        + "surchargeTdsAmt='"+txt_surchargeTdsAmt.getText()+"',"
                        + "educationTdsAmt='"+txt_eduTdsAmt.getText()+"',"
                        + "branch='"+txt_branch.getText()+"',"
                        + "department='"+txt_department.getText()+"',"
                        + "segment='"+txt_segment.getText()+"',"
                        + "product='"+txt_product.getText()+"',"
                        + "narration='"+txt_narration.getText()+"'where ledgerCodeCr='"+txt_crLedgerCode.getText()+"'";
                PreparedStatement stmt = con.prepareStatement(str);
                stmt.executeUpdate();
                JOptionPane.showMessageDialog(this, "Voucher updated successfully");
                
//                    txt_receipt.setText("**********************************************************************************************************\n");
//                    txt_receipt.setText(txt_receipt.getText()+"\t\t\s\s Voucher Receipt \n");
//                    txt_receipt.setText(txt_receipt.getText()+"**********************************************************************************************************\n");
//                   
//                    txt_receipt.setText(txt_receipt.getText()+"\s\sLedger Code(cr) :"+txt_crLedgerCode.getText()+"\n");
//                    txt_receipt.setText(txt_receipt.getText()+"\s\sName Code(cr) :"+txt_CrLedgerName.getText()+"\n");
//                    txt_receipt.setText(txt_receipt.getText()+"\s\sAmount(cr) :"+txt_CrAmt.getText()+"\n");
//                    txt_receipt.setText(txt_receipt.getText()+"\s\sLedger Code(dr) :"+txt_drLedgerCode.getText()+"\n");
//                    txt_receipt.setText(txt_receipt.getText()+"\s\sLedger Name(dr) :"+txt_DrLedgerName.getText()+"\n");
//                    txt_receipt.setText(txt_receipt.getText()+"\s\sAmount :"+txt_DrAmt.getText()+"\n");
//                    txt_receipt.setText(txt_receipt.getText()+"\s\sCheque No. :"+txt_ChequeNo.getText()+"\n");
//                    txt_receipt.setText(txt_receipt.getText()+"\s\sDrawn on :"+txt_drawnon.getText()+"\n");
//                    txt_receipt.setText(txt_receipt.getText()+"\s\sBranch :"+txt_chequeBranch.getText()+"\n");
//                    txt_receipt.setText(txt_receipt.getText()+"\s\sGST Code :"+txt_gstcode.getText()+"\n");
//                    txt_receipt.setText(txt_receipt.getText()+"\s\sCGST Code :"+txt_cgstCode.getText()+"\n");
//                    txt_receipt.setText(txt_receipt.getText()+"\s\sSGST Code :"+txt_sgstCode.getText()+"\n");
//                    txt_receipt.setText(txt_receipt.getText()+"\s\sIGST Code :"+txt_igstCode.getText()+"\n");
//                    txt_receipt.setText(txt_receipt.getText()+"\s\sTDS :"+txt_tds.getText()+"\n");
//                    txt_receipt.setText(txt_receipt.getText()+"\s\sTDS Code :"+txt_tdsCode.getText()+"\n");
//                    txt_receipt.setText(txt_receipt.getText()+"\s\sTDS rate :"+txt_tdsRate.getText()+"\n");
//                    txt_receipt.setText(txt_receipt.getText()+"\s\sBasic TDS amt :"+txt_basicTdsAmt.getText()+"\n");
//                    txt_receipt.setText(txt_receipt.getText()+"\s\sSurcharge TDS amt :"+txt_surchargeTdsAmt.getText()+"\n");
//                    txt_receipt.setText(txt_receipt.getText()+"\s\sEdu TDS amt :"+txt_eduTdsAmt.getText()+"\n");
//                    txt_receipt.setText(txt_receipt.getText()+"\s\sBranch :"+txt_branch.getText()+"\n");
//                    txt_receipt.setText(txt_receipt.getText()+"\s\sDepartment :"+txt_department.getText()+"\n");
//                    txt_receipt.setText(txt_receipt.getText()+"\s\sSegment :"+txt_segment.getText()+"\n");
//                    txt_receipt.setText(txt_receipt.getText()+"\s\sProduct :"+txt_product.getText()+"\n");
//                    txt_receipt.setText(txt_receipt.getText()+"\s\sNarration :"+txt_narration.getText()+"\n");


                      txt_receipt.append("*********************************************************************************************************\n" +
                                "\t\t\s\s\s\s\s\s\s\s\s\s\s Voucher Receipt\n" +
                                "*********************************************************************************************************\n\n" +
                              
                              "\s\s\s\s\s\sLedger Code(cr) :"+txt_crLedgerCode.getText() + "\n\n" + 
                              "\s\s\s\s\s\sLedger Name(cr) :"+txt_crLedgerName.getText() + "\n\n" +
                              "\s\s\s\s\s\sAmount :"+txt_crAmt.getText() + "\n\n");
                              
//                                "\s\s\s\s\s\s\s\s\s\sLedger Code" + "\t\s\s\s\s\s\s\s\s\s\sLedger Name" + "\t\s\s\s\s\s\s\s\s\s\sAmount\n" +
//                                "\s\s\s\s\s\s\s\s\s\s---------------------------------------------------------------------------------------------------\n" +
//                                "\s\s\s\s\s\s\s\s\s\s"+txt_crLedgerCode.getText() + "\t\t\t"+txt_crLedgerName.getText() + "\t\t\s\s\s\s\s\s\s\s\s\s\s"+txt_crAmt.getText() + "\n\n" + 
//                                "\s\s\s\s\s\s\s\s\s\s"+txt_drLedgerCode.getText() + "\t\t\s\s\s\s\s\s\s\s\s\s\s"+txt_drLedgerName.getText() + "\t\t\s\s\s\s\s\s\s\s\s\s\s"+txt_drAmt.getText() + "\n\n\n" +
//                                "\s\s\s\s\s\s\s\s\s\sNarration:\n" +
//                                "\s\s\s\s\s\s\s\s\s\s"+txt_narration.getText());
                    
                        txt_crLedgerCode.setText("");
                        txt_crLedgerName.setText("");
                        txt_crAmt.setText("");
                        txt_drLedgerCode.setText("");
                        txt_drLedgerName.setText("");
                        txt_drAmt.setText("");
                        txt_ChequeNo.setText("");
                        chq_date.setCalendar(null);
                        txt_drawnon.setText("");
                        txt_chequeBranch.setText("");
                        txt_gstcode.setText("");
                        txt_cgstCode.setText("");
                        txt_sgstCode.setText("");
                        txt_igstCode.setText("");
                        txt_tds.setText("");
                        txt_tdsCode.setText("");
                        txt_tdsRate.setText("");
                        txt_basicTdsAmt.setText("");
                        txt_surchargeTdsAmt.setText("");
                        txt_eduTdsAmt.setText("");
                        txt_branch.setText("");
                        txt_department.setText("");
                        txt_segment.setText("");
                        txt_product.setText("");
                        txt_narration.setText("");
                } catch (SQLException ex) {
                    Logger.getLogger(CreateVoucher.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
    }//GEN-LAST:event_btn_updateVoucherActionPerformed

    private void btn_deleteVoucherActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_deleteVoucherActionPerformed
        // TODO add your handling code here:
        String ledgerCodeCr = txt_crLedgerCode.getText();
        String ledgerNameCr = txt_crLedgerName.getText();
        String crAmount = txt_crAmt.getText();
        String ledgerCodeDr = txt_drLedgerCode.getText();
        String ledgerNameDr = txt_drLedgerName.getText();
        String drAmount = txt_crAmt.getText();
        String chqNo = txt_ChequeNo.getText();
            java.util.Date chqdate= chq_date.getDate();
            SimpleDateFormat oDateFormat = new SimpleDateFormat("dd/MM/y");
        String ChqDate = oDateFormat.format(chqdate.getDate());
        String drawnOn = txt_drawnon.getText();
        String chqBranch = txt_chequeBranch.getText();
        String gstCode = txt_gstcode.getText();
        String cgstCode = txt_cgstCode.getText();
        String sgstCode = txt_sgstCode.getText();
        String igstCode = txt_igstCode.getText();
        String tds = txt_tds.getText();
        String tdsCode = txt_tdsCode.getText();
        String tdsRate = txt_tdsRate.getText();
        String basicTdsAmt = txt_basicTdsAmt.getText();
        String surchargeTdsAmt = txt_surchargeTdsAmt.getText();
        String educationTdsAmt = txt_eduTdsAmt.getText();
        String branch = txt_branch.getText();
        String department = txt_department.getText();
        String segment = txt_segment.getText();
        String product = txt_product.getText();
        String narration = txt_narration.getText();
        if(ledgerCodeCr.equals("") || ledgerNameCr.equals("") || crAmount.equals("") || ledgerCodeDr.equals("") || ledgerNameDr.equals("") || 
                drAmount.equals("") || chqNo.equals("") || chqdate.equals("") || drawnOn.equals("") || chqBranch.equals("") || gstCode.equals("") ||
                cgstCode.equals("") || sgstCode.equals("") || igstCode.equals("") || tds.equals("") || tdsCode.equals("") || tdsRate.equals("") ||
                basicTdsAmt.equals("") || surchargeTdsAmt.equals("") || educationTdsAmt.equals("") || branch.equals("") || department.equals("") ||
                segment.equals("") || product.equals("") || narration.equals(""))
        {
            JOptionPane.showMessageDialog(rootPane, "No Data Found");
        }
        else{
                    try {
                            DBConnection dbc = new DBConnection();
                            Connection con = dbc.dbconnect();
                            String str = "Delete from voucher where ledgerCodeCr='"+txt_crLedgerCode.getText()+"'";
                            PreparedStatement stmt = con.prepareStatement(str);
                            stmt.executeUpdate();
                            JOptionPane.showMessageDialog(this, "Voucher record deleted successfully");
                                txt_crLedgerCode.setText("");
                                txt_crLedgerName.setText("");
                                txt_crAmt.setText("");
                                txt_drLedgerCode.setText("");
                                txt_drLedgerName.setText("");
                                txt_drAmt.setText("");
                                txt_ChequeNo.setText("");
                                chq_date.setCalendar(null);
                                txt_drawnon.setText("");
                                txt_chequeBranch.setText("");
                                txt_gstcode.setText("");
                                txt_cgstCode.setText("");
                                txt_sgstCode.setText("");
                                txt_igstCode.setText("");
                                txt_tds.setText("");
                                txt_tdsCode.setText("");
                                txt_tdsRate.setText("");
                                txt_basicTdsAmt.setText("");
                                txt_surchargeTdsAmt.setText("");
                                txt_eduTdsAmt.setText("");
                                txt_branch.setText("");
                                txt_department.setText("");
                                txt_segment.setText("");
                                txt_product.setText("");
                                txt_narration.setText("");
                            con.close();
                        } catch (SQLException ex) {
                            Logger.getLogger(CreateVoucher.class.getName()).log(Level.SEVERE, null, ex);
                        }
            }
        
    }//GEN-LAST:event_btn_deleteVoucherActionPerformed

    private void btn_printVoucherActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_printVoucherActionPerformed
        try {
            // TODO add your handling code here:
            txt_receipt.print();
        } catch (PrinterException ex) {
            Logger.getLogger(CreateVoucher.class.getName()).log(Level.SEVERE, null, ex);
        }

//            PrinterJob job = PrinterJob.getPrinterJob();
//            job.setJobName("Print Data");
//            
//            job.setPrintable(new Printable(){
//            public int print(Graphics pg,PageFormat pf, int pageNum){
//                    pf.setOrientation(PageFormat.LANDSCAPE);
//                 if(pageNum > 0){
//                    return Printable.NO_SUCH_PAGE;
//                }
//                
//                Graphics2D g2 = (Graphics2D)pg;
//                g2.translate(pf.getImageableX(), pf.getImageableY());
//                g2.scale(0.47,0.47);
//                
//                txt_receipt.print(g2);
//         
//               
//                return Printable.PAGE_EXISTS;
//                         
//                
//            }
//    });
//            boolean ok = job.printDialog();
//        if(ok){
//        try{
//            
//        job.print();
//        }
//        catch (PrinterException ex){
//	ex.printStackTrace();
//}
//        }
    }//GEN-LAST:event_btn_printVoucherActionPerformed

    private void txt_chequeBranchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_chequeBranchActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_chequeBranchActionPerformed

    private void txt_crLedgerCodeInputMethodTextChanged(java.awt.event.InputMethodEvent evt) {//GEN-FIRST:event_txt_crLedgerCodeInputMethodTextChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_crLedgerCodeInputMethodTextChanged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CreateVoucher.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CreateVoucher.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CreateVoucher.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CreateVoucher.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CreateVoucher().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_cancel;
    private javax.swing.JButton btn_createVoucher;
    private javax.swing.JButton btn_deleteVoucher;
    private javax.swing.JButton btn_findVoucher;
    private javax.swing.JButton btn_printVoucher;
    private javax.swing.JButton btn_updateVoucher;
    private com.toedter.calendar.JDateChooser chq_date;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lbl_ChequeDate;
    private javax.swing.JLabel lbl_ChequeNo;
    private javax.swing.JLabel lbl_basicTdsAmt;
    private javax.swing.JLabel lbl_branch;
    private javax.swing.JLabel lbl_cgstCode;
    private javax.swing.JLabel lbl_chequeBranch;
    private javax.swing.JLabel lbl_department;
    private javax.swing.JLabel lbl_drawnon;
    private javax.swing.JLabel lbl_eduTdsAmt;
    private javax.swing.JLabel lbl_gstcode;
    private javax.swing.JLabel lbl_igstCode;
    private javax.swing.JLabel lbl_ledgerCrAmt;
    private javax.swing.JLabel lbl_ledgerCrCode;
    private javax.swing.JLabel lbl_ledgerCrCode1;
    private javax.swing.JLabel lbl_ledgerCrName;
    private javax.swing.JLabel lbl_ledgerDrAmt;
    private javax.swing.JLabel lbl_ledgerDrCode;
    private javax.swing.JLabel lbl_ledgerDrName;
    private javax.swing.JLabel lbl_narration;
    private javax.swing.JLabel lbl_product;
    private javax.swing.JLabel lbl_segment;
    private javax.swing.JLabel lbl_sgstCode;
    private javax.swing.JLabel lbl_surchargeTdsAmt;
    private javax.swing.JLabel lbl_tds;
    private javax.swing.JLabel lbl_tdsCode;
    private javax.swing.JLabel lbl_tdsRate;
    private javax.swing.JTextField txt_ChequeNo;
    private javax.swing.JTextField txt_basicTdsAmt;
    private javax.swing.JTextField txt_branch;
    private javax.swing.JTextField txt_cgstCode;
    private javax.swing.JTextField txt_chequeBranch;
    private javax.swing.JTextField txt_crAmt;
    private javax.swing.JTextField txt_crLedgerCode;
    private javax.swing.JTextField txt_crLedgerName;
    private javax.swing.JTextField txt_department;
    private javax.swing.JTextField txt_drAmt;
    private javax.swing.JTextField txt_drLedgerCode;
    private javax.swing.JTextField txt_drLedgerName;
    private javax.swing.JTextField txt_drawnon;
    private javax.swing.JTextField txt_eduTdsAmt;
    private javax.swing.JTextField txt_gstcode;
    private javax.swing.JTextField txt_igstCode;
    private javax.swing.JTextArea txt_narration;
    private javax.swing.JTextField txt_product;
    private javax.swing.JTextArea txt_receipt;
    private javax.swing.JTextField txt_segment;
    private javax.swing.JTextField txt_sgstCode;
    private javax.swing.JTextField txt_surchargeTdsAmt;
    private javax.swing.JTextField txt_tds;
    private javax.swing.JTextField txt_tdsCode;
    private javax.swing.JTextField txt_tdsRate;
    private javax.swing.JTextField txt_voucherCode;
    // End of variables declaration//GEN-END:variables
}
