/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.nibbannews;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author Admin
 */
public class GroupMaster extends javax.swing.JFrame {

    /**
     * Creates new form GroupMaster
     */
    public GroupMaster() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lbl_ledgerCrCode = new javax.swing.JLabel();
        txt_GroupCode = new javax.swing.JTextField();
        lbl_ledgerCrName = new javax.swing.JLabel();
        txt_GroupName = new javax.swing.JTextField();
        lbl_ledgerCrCode1 = new javax.swing.JLabel();
        lbl_ledgerCrName1 = new javax.swing.JLabel();
        txt_primaryGrpCode = new javax.swing.JTextField();
        txt_primaryGrpName = new javax.swing.JTextField();
        btn_createGroup = new javax.swing.JButton();
        btn_findGroup = new javax.swing.JButton();
        btn_updateGroup = new javax.swing.JButton();
        btn_deleteGroup = new javax.swing.JButton();
        btn_cancel = new javax.swing.JButton();
        lbl_ledgerCrName11 = new javax.swing.JLabel();
        lbl_ledgerCrName12 = new javax.swing.JLabel();
        lbl_ledgerCrName13 = new javax.swing.JLabel();
        cb_netdcBalance = new javax.swing.JComboBox<>();
        cb_usedForCal = new javax.swing.JComboBox<>();
        cb_setAlterTDS = new javax.swing.JComboBox<>();
        lbl_ledgerCrName14 = new javax.swing.JLabel();
        cb_behavesLike = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Group Master");

        jPanel1.setBackground(new java.awt.Color(52, 51, 52));

        lbl_ledgerCrCode.setBackground(new java.awt.Color(255, 255, 255));
        lbl_ledgerCrCode.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        lbl_ledgerCrCode.setForeground(new java.awt.Color(255, 255, 255));
        lbl_ledgerCrCode.setText("Group Code");

        txt_GroupCode.setBackground(new java.awt.Color(52, 51, 52));
        txt_GroupCode.setForeground(new java.awt.Color(255, 255, 255));
        txt_GroupCode.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(255, 255, 255)));
        txt_GroupCode.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_GroupCodeActionPerformed(evt);
            }
        });

        lbl_ledgerCrName.setBackground(new java.awt.Color(255, 255, 255));
        lbl_ledgerCrName.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        lbl_ledgerCrName.setForeground(new java.awt.Color(255, 255, 255));
        lbl_ledgerCrName.setText("Group Name");

        txt_GroupName.setBackground(new java.awt.Color(52, 51, 52));
        txt_GroupName.setForeground(new java.awt.Color(255, 255, 255));
        txt_GroupName.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(255, 255, 255)));
        txt_GroupName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_GroupNameActionPerformed(evt);
            }
        });

        lbl_ledgerCrCode1.setBackground(new java.awt.Color(255, 255, 255));
        lbl_ledgerCrCode1.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        lbl_ledgerCrCode1.setForeground(new java.awt.Color(255, 255, 255));
        lbl_ledgerCrCode1.setText("Primary Group Code");

        lbl_ledgerCrName1.setBackground(new java.awt.Color(255, 255, 255));
        lbl_ledgerCrName1.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        lbl_ledgerCrName1.setForeground(new java.awt.Color(255, 255, 255));
        lbl_ledgerCrName1.setText("Primary Group Name");

        txt_primaryGrpCode.setBackground(new java.awt.Color(52, 51, 52));
        txt_primaryGrpCode.setForeground(new java.awt.Color(255, 255, 255));
        txt_primaryGrpCode.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(255, 255, 255)));
        txt_primaryGrpCode.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_primaryGrpCodeActionPerformed(evt);
            }
        });

        txt_primaryGrpName.setBackground(new java.awt.Color(52, 51, 52));
        txt_primaryGrpName.setForeground(new java.awt.Color(255, 255, 255));
        txt_primaryGrpName.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(255, 255, 255)));
        txt_primaryGrpName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_primaryGrpNameActionPerformed(evt);
            }
        });

        btn_createGroup.setBackground(new java.awt.Color(52, 51, 52));
        btn_createGroup.setForeground(new java.awt.Color(255, 255, 255));
        btn_createGroup.setText("Create Group");
        btn_createGroup.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_createGroup.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_createGroupActionPerformed(evt);
            }
        });

        btn_findGroup.setBackground(new java.awt.Color(52, 51, 52));
        btn_findGroup.setForeground(new java.awt.Color(255, 255, 255));
        btn_findGroup.setText("Find Group");
        btn_findGroup.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_findGroup.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_findGroupActionPerformed(evt);
            }
        });

        btn_updateGroup.setBackground(new java.awt.Color(52, 51, 52));
        btn_updateGroup.setForeground(new java.awt.Color(255, 255, 255));
        btn_updateGroup.setText("Update Group");
        btn_updateGroup.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_updateGroup.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_updateGroupActionPerformed(evt);
            }
        });

        btn_deleteGroup.setBackground(new java.awt.Color(52, 51, 52));
        btn_deleteGroup.setForeground(new java.awt.Color(255, 255, 255));
        btn_deleteGroup.setText("Delete Group");
        btn_deleteGroup.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_deleteGroup.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_deleteGroupActionPerformed(evt);
            }
        });

        btn_cancel.setBackground(new java.awt.Color(52, 51, 52));
        btn_cancel.setForeground(new java.awt.Color(255, 255, 255));
        btn_cancel.setText("Cancel");
        btn_cancel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_cancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_cancelActionPerformed(evt);
            }
        });

        lbl_ledgerCrName11.setBackground(new java.awt.Color(255, 255, 255));
        lbl_ledgerCrName11.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        lbl_ledgerCrName11.setForeground(new java.awt.Color(255, 255, 255));
        lbl_ledgerCrName11.setText("Net Debit/Credit balance for");

        lbl_ledgerCrName12.setBackground(new java.awt.Color(255, 255, 255));
        lbl_ledgerCrName12.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        lbl_ledgerCrName12.setForeground(new java.awt.Color(255, 255, 255));
        lbl_ledgerCrName12.setText("used for calculation");

        lbl_ledgerCrName13.setBackground(new java.awt.Color(255, 255, 255));
        lbl_ledgerCrName13.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        lbl_ledgerCrName13.setForeground(new java.awt.Color(255, 255, 255));
        lbl_ledgerCrName13.setText("Set Alter TDS & Debits");

        cb_netdcBalance.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "select", "Yes", "No" }));

        cb_usedForCal.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "select", "Yes", "No" }));

        cb_setAlterTDS.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "select", "Yes", "No" }));

        lbl_ledgerCrName14.setBackground(new java.awt.Color(255, 255, 255));
        lbl_ledgerCrName14.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        lbl_ledgerCrName14.setForeground(new java.awt.Color(255, 255, 255));
        lbl_ledgerCrName14.setText("behaves like sub-ledger");

        cb_behavesLike.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "select", "Yes", "No" }));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(82, 82, 82)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(178, 178, 178)
                                .addComponent(cb_behavesLike, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lbl_ledgerCrName)
                                    .addComponent(lbl_ledgerCrCode)
                                    .addComponent(lbl_ledgerCrCode1)
                                    .addComponent(lbl_ledgerCrName1)
                                    .addComponent(lbl_ledgerCrName14))
                                .addGap(48, 48, 48)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txt_primaryGrpName)
                                    .addComponent(txt_GroupCode)
                                    .addComponent(txt_GroupName)
                                    .addComponent(txt_primaryGrpCode, javax.swing.GroupLayout.PREFERRED_SIZE, 249, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lbl_ledgerCrName11)
                                    .addComponent(lbl_ledgerCrName12)
                                    .addComponent(lbl_ledgerCrName13))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(cb_usedForCal, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(cb_netdcBalance, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(cb_setAlterTDS, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(btn_createGroup)
                        .addGap(18, 18, 18)
                        .addComponent(btn_findGroup)
                        .addGap(18, 18, 18)
                        .addComponent(btn_updateGroup)
                        .addGap(18, 18, 18)
                        .addComponent(btn_deleteGroup)
                        .addGap(18, 18, 18)
                        .addComponent(btn_cancel)))
                .addGap(0, 34, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(54, 54, 54)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_ledgerCrCode, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_GroupCode, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_ledgerCrName)
                    .addComponent(txt_GroupName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_ledgerCrCode1)
                    .addComponent(txt_primaryGrpCode, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_ledgerCrName1)
                    .addComponent(txt_primaryGrpName, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cb_behavesLike, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl_ledgerCrName14))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_ledgerCrName11)
                    .addComponent(cb_netdcBalance, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_ledgerCrName12)
                    .addComponent(cb_usedForCal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_ledgerCrName13)
                    .addComponent(cb_setAlterTDS, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_updateGroup, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_findGroup, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_deleteGroup, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_createGroup, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_cancel, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(35, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void txt_GroupCodeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_GroupCodeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_GroupCodeActionPerformed

    private void txt_GroupNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_GroupNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_GroupNameActionPerformed

    private void txt_primaryGrpCodeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_primaryGrpCodeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_primaryGrpCodeActionPerformed

    private void txt_primaryGrpNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_primaryGrpNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_primaryGrpNameActionPerformed

    private void btn_createGroupActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_createGroupActionPerformed
        // TODO add your handling code here:
        String grpCode = txt_GroupCode.getText();
        String grpName = txt_GroupName.getText();
        String primaryGrpCode = txt_primaryGrpCode.getText();
        String primaryGrpName = txt_primaryGrpName.getText();
        String behavesLikeSub_Ledger = cb_behavesLike.getSelectedItem().toString();
        String netDrCrBalance = cb_netdcBalance.getSelectedItem().toString();
        String usedForCalc = cb_usedForCal.getSelectedItem().toString();
        String setAlterTDS = cb_setAlterTDS.getSelectedItem().toString();
        if(grpCode.equals("") || grpName.equals("") || primaryGrpCode.equals("") || primaryGrpName.equals("") || behavesLikeSub_Ledger.equals("select") || 
                 netDrCrBalance.equals("select") || usedForCalc.equals("select") || setAlterTDS.equals("select")){
            JOptionPane.showMessageDialog(rootPane, "All feilds are required");
        }
        else{
            try {
                DBConnection dbc = new DBConnection();
                Connection con = dbc.dbconnect();
                String str = "insert into group_master values(?,?,?,?,?,?,?,?)";
                PreparedStatement stmt = con.prepareStatement(str);
                stmt.setString(1, txt_GroupCode.getText());
                stmt.setString(2, txt_GroupName.getText());
                stmt.setString(3, txt_primaryGrpCode.getText());
                stmt.setString(4, txt_primaryGrpName.getText());
                
                String behaveslike_value = cb_behavesLike.getSelectedItem().toString();
                stmt.setString(5, behaveslike_value);
                
                String netDrCrBalance_value = cb_netdcBalance.getSelectedItem().toString();
                stmt.setString(6, netDrCrBalance_value);
                
                String usedForCalc_value = cb_usedForCal.getSelectedItem().toString();
                stmt.setString(7, usedForCalc_value);
                
                String setAlterTDS_value = cb_setAlterTDS.getSelectedItem().toString();
                stmt.setString(8, setAlterTDS_value);
                stmt.executeUpdate();
                JOptionPane.showMessageDialog(this, "Employee Added Successfully");
                txt_GroupCode.setText("");
                txt_GroupName.setText("");
                txt_primaryGrpCode.setText("");
                txt_primaryGrpName.setText("");
                cb_behavesLike.setSelectedIndex(0);
                cb_netdcBalance.setSelectedIndex(0);
                cb_usedForCal.setSelectedIndex(0);
                cb_setAlterTDS.setSelectedIndex(0);
                } 
                catch (SQLException ex) {
                    Logger.getLogger(GroupMaster.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_btn_createGroupActionPerformed

    private void btn_findGroupActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_findGroupActionPerformed
        // TODO add your handling code here:
        String grpCode = txt_GroupCode.getText();
        if(grpCode.equals("")){
            JOptionPane.showMessageDialog(rootPane, "Enter Group code to search the Group Entry");
        }
        else{
        try {
            DBConnection dbc = new DBConnection();
            Connection con = dbc.dbconnect();
            String str = "select * from group_master where groupCode=?";
            PreparedStatement stmt = con.prepareStatement(str);
            stmt.setString(1, txt_GroupCode.getText());
            ResultSet rs =  stmt.executeQuery();
            if(rs.next()){
                txt_GroupName.setText(rs.getString("groupName"));
                txt_primaryGrpCode.setText(rs.getString("primaryGroupCode"));
                txt_primaryGrpName.setText(rs.getString("primaryGroupName"));
                
                String behaveslike_value = rs.getString("behavesLikeSubLedger");
                cb_behavesLike.addItem(behaveslike_value);
                
                String netDrCrBalance_value = rs.getString("netdcBalance");
                cb_netdcBalance.addItem(netDrCrBalance_value);
                
                String usedForCalc_value = rs.getString("usedForCalculation");
                cb_usedForCal.addItem(usedForCalc_value);
                
                String setAlterTDS_value = rs.getString("setAlterTdsDebit");
                cb_setAlterTDS.addItem(setAlterTDS_value);
            }
            else{
                JOptionPane.showMessageDialog(this, "NO Data found!");
            }
        } catch (SQLException ex) {
            Logger.getLogger(GroupMaster.class.getName()).log(Level.SEVERE, null, ex);
        }
        }
    }//GEN-LAST:event_btn_findGroupActionPerformed

    private void btn_updateGroupActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_updateGroupActionPerformed
        // TODO add your handling code here:
        String grpCode = txt_GroupCode.getText();
        String grpName = txt_GroupName.getText();
        String primaryGrpCode = txt_primaryGrpCode.getText();
        String primaryGrpName = txt_primaryGrpName.getText();
        String behavesLikeSub_Ledger = cb_behavesLike.getSelectedItem().toString();
        String netDrCrBalance = cb_netdcBalance.getSelectedItem().toString();
        String usedForCalc = cb_usedForCal.getSelectedItem().toString();
        String setAlterTDS = cb_setAlterTDS.getSelectedItem().toString();
        if(grpCode.equals("") || grpName.equals("") || primaryGrpCode.equals("") || primaryGrpName.equals("") || behavesLikeSub_Ledger.equals("select") || 
                 netDrCrBalance.equals("select") || usedForCalc.equals("select") || setAlterTDS.equals("select")){
            JOptionPane.showMessageDialog(rootPane, "All feilds are required");
        }
        else{
            try {
                DBConnection dbc = new DBConnection();
                Connection con = dbc.dbconnect();
                String str = "Update group_master set groupName='"+txt_GroupName.getText()+"',"
                        + "primaryGroupCode='"+txt_primaryGrpCode.getText()+"',"
                        + "primaryGroupName='"+txt_primaryGrpName.getText()+"',"
                        + "behavesLikeSubLedger='"+cb_behavesLike.getSelectedItem()+"',"
                        + "netdcBalance='"+cb_netdcBalance.getSelectedItem()+"',"
                        + "usedForCalculation='"+cb_usedForCal.getSelectedItem()+"',"
                        + "setAlterTdsDebit='"+cb_setAlterTDS.getSelectedItem()+"'where groupCode='"+txt_GroupCode.getText()+"'";
                PreparedStatement stmt = con.prepareStatement(str);
                stmt.executeUpdate();
                JOptionPane.showMessageDialog(this, "Data updated successfully");
                txt_GroupCode.setText("");
                txt_GroupName.setText("");
                txt_primaryGrpCode.setText("");
                txt_primaryGrpName.setText("");
                cb_behavesLike.setSelectedIndex(0);
                cb_netdcBalance.setSelectedIndex(0);
                cb_usedForCal.setSelectedIndex(0);
                cb_setAlterTDS.setSelectedIndex(0);
                } catch (SQLException ex) {
                    Logger.getLogger(GroupMaster.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
    }//GEN-LAST:event_btn_updateGroupActionPerformed

    private void btn_deleteGroupActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_deleteGroupActionPerformed
        // TODO add your handling code here:
        String grpCode = txt_GroupCode.getText();
        String grpName = txt_GroupName.getText();
        String primaryGrpCode = txt_primaryGrpCode.getText();
        String primaryGrpName = txt_primaryGrpName.getText();
        String behavesLikeSub_Ledger = cb_behavesLike.getSelectedItem().toString();
        String netDrCrBalance = cb_netdcBalance.getSelectedItem().toString();
        String usedForCalc = cb_usedForCal.getSelectedItem().toString();
        String setAlterTDS = cb_setAlterTDS.getSelectedItem().toString();
        if(grpCode.equals("") || grpName.equals("") || primaryGrpCode.equals("") || primaryGrpName.equals("") || behavesLikeSub_Ledger.equals("select") || 
                 netDrCrBalance.equals("select") || usedForCalc.equals("select") || setAlterTDS.equals("select")){
            JOptionPane.showMessageDialog(rootPane, "All feilds are required");
        }
        else{
            try {
                DBConnection dbc = new DBConnection();
                Connection con = dbc.dbconnect();
                String str = "Delete from group_master where groupCode='"+txt_GroupCode.getText()+"'";
                PreparedStatement stmt = con.prepareStatement(str);
                stmt.executeUpdate();
                JOptionPane.showMessageDialog(this, "Employee record deleted successfully");
                txt_GroupCode.setText("");
                txt_GroupName.setText("");
                txt_primaryGrpCode.setText("");
                txt_primaryGrpName.setText("");
                cb_behavesLike.setSelectedIndex(0);
                cb_netdcBalance.setSelectedIndex(0);
                cb_usedForCal.setSelectedIndex(0);
                cb_setAlterTDS.setSelectedIndex(0);
                con.close();
                } 
                catch (SQLException ex) {
                    Logger.getLogger(GroupMaster.class.getName()).log(Level.SEVERE, null, ex);
            }
         }
    }//GEN-LAST:event_btn_deleteGroupActionPerformed

    private void btn_cancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_cancelActionPerformed
        // TODO add your handling code here:
        //        new AccountMaster().setVisible(true);
        dispose();
    }//GEN-LAST:event_btn_cancelActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GroupMaster.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GroupMaster.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GroupMaster.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GroupMaster.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GroupMaster().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_cancel;
    private javax.swing.JButton btn_createGroup;
    private javax.swing.JButton btn_deleteGroup;
    private javax.swing.JButton btn_findGroup;
    private javax.swing.JButton btn_updateGroup;
    private javax.swing.JComboBox<String> cb_behavesLike;
    private javax.swing.JComboBox<String> cb_netdcBalance;
    private javax.swing.JComboBox<String> cb_setAlterTDS;
    private javax.swing.JComboBox<String> cb_usedForCal;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lbl_ledgerCrCode;
    private javax.swing.JLabel lbl_ledgerCrCode1;
    private javax.swing.JLabel lbl_ledgerCrName;
    private javax.swing.JLabel lbl_ledgerCrName1;
    private javax.swing.JLabel lbl_ledgerCrName11;
    private javax.swing.JLabel lbl_ledgerCrName12;
    private javax.swing.JLabel lbl_ledgerCrName13;
    private javax.swing.JLabel lbl_ledgerCrName14;
    private javax.swing.JTextField txt_GroupCode;
    private javax.swing.JTextField txt_GroupName;
    private javax.swing.JTextField txt_primaryGrpCode;
    private javax.swing.JTextField txt_primaryGrpName;
    // End of variables declaration//GEN-END:variables
}
