/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.nibbannews;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author Admin
 */
public class GstMaster extends javax.swing.JFrame {

    /**
     * Creates new form GstMaster
     */
    public GstMaster() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lbl_GSTCatCode = new javax.swing.JLabel();
        txt_GstCatCode = new javax.swing.JTextField();
        lbl_GSTCatName = new javax.swing.JLabel();
        txt_GstCatName = new javax.swing.JTextField();
        lbl_input = new javax.swing.JLabel();
        txt_input = new javax.swing.JTextField();
        txt_output = new javax.swing.JTextField();
        lbl_output = new javax.swing.JLabel();
        lbl_ledgerCrCode4 = new javax.swing.JLabel();
        lbl_input1 = new javax.swing.JLabel();
        lbl_output1 = new javax.swing.JLabel();
        lbl_ledgerCrCode7 = new javax.swing.JLabel();
        txt_inputCgst = new javax.swing.JTextField();
        txt_outputCgst = new javax.swing.JTextField();
        lbl_ledgerCrCode8 = new javax.swing.JLabel();
        txt_inputSgst = new javax.swing.JTextField();
        txt_outputSgst = new javax.swing.JTextField();
        lbl_ledgerCrCode9 = new javax.swing.JLabel();
        txt_inputIgst = new javax.swing.JTextField();
        txt_outputIgst = new javax.swing.JTextField();
        btn_createMaster = new javax.swing.JButton();
        btn_findMaster = new javax.swing.JButton();
        btn_updateMaster = new javax.swing.JButton();
        btn_deleteMaster = new javax.swing.JButton();
        btn_cancel = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("GST Master");

        jPanel1.setBackground(new java.awt.Color(52, 51, 52));

        lbl_GSTCatCode.setBackground(new java.awt.Color(255, 255, 255));
        lbl_GSTCatCode.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        lbl_GSTCatCode.setForeground(new java.awt.Color(255, 255, 255));
        lbl_GSTCatCode.setText("GST Category Code");

        txt_GstCatCode.setBackground(new java.awt.Color(52, 51, 52));
        txt_GstCatCode.setForeground(new java.awt.Color(255, 255, 255));
        txt_GstCatCode.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(255, 255, 255)));
        txt_GstCatCode.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_GstCatCodeActionPerformed(evt);
            }
        });

        lbl_GSTCatName.setBackground(new java.awt.Color(255, 255, 255));
        lbl_GSTCatName.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        lbl_GSTCatName.setForeground(new java.awt.Color(255, 255, 255));
        lbl_GSTCatName.setText("GST Category Name");

        txt_GstCatName.setBackground(new java.awt.Color(52, 51, 52));
        txt_GstCatName.setForeground(new java.awt.Color(255, 255, 255));
        txt_GstCatName.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(255, 255, 255)));
        txt_GstCatName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_GstCatNameActionPerformed(evt);
            }
        });

        lbl_input.setBackground(new java.awt.Color(255, 255, 255));
        lbl_input.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        lbl_input.setForeground(new java.awt.Color(255, 255, 255));
        lbl_input.setText("Input");

        txt_input.setBackground(new java.awt.Color(52, 51, 52));
        txt_input.setForeground(new java.awt.Color(255, 255, 255));
        txt_input.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(255, 255, 255)));
        txt_input.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_inputActionPerformed(evt);
            }
        });

        txt_output.setBackground(new java.awt.Color(52, 51, 52));
        txt_output.setForeground(new java.awt.Color(255, 255, 255));
        txt_output.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(255, 255, 255)));
        txt_output.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_outputActionPerformed(evt);
            }
        });

        lbl_output.setBackground(new java.awt.Color(255, 255, 255));
        lbl_output.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        lbl_output.setForeground(new java.awt.Color(255, 255, 255));
        lbl_output.setText("Output");

        lbl_ledgerCrCode4.setBackground(new java.awt.Color(255, 255, 255));
        lbl_ledgerCrCode4.setFont(new java.awt.Font("Calibri", 1, 15)); // NOI18N
        lbl_ledgerCrCode4.setForeground(new java.awt.Color(255, 255, 255));
        lbl_ledgerCrCode4.setText("GST rate");

        lbl_input1.setBackground(new java.awt.Color(255, 255, 255));
        lbl_input1.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        lbl_input1.setForeground(new java.awt.Color(255, 255, 255));
        lbl_input1.setText("Input");

        lbl_output1.setBackground(new java.awt.Color(255, 255, 255));
        lbl_output1.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        lbl_output1.setForeground(new java.awt.Color(255, 255, 255));
        lbl_output1.setText("Output");

        lbl_ledgerCrCode7.setBackground(new java.awt.Color(255, 255, 255));
        lbl_ledgerCrCode7.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        lbl_ledgerCrCode7.setForeground(new java.awt.Color(255, 255, 255));
        lbl_ledgerCrCode7.setText("CGST");

        txt_inputCgst.setBackground(new java.awt.Color(52, 51, 52));
        txt_inputCgst.setForeground(new java.awt.Color(255, 255, 255));
        txt_inputCgst.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(255, 255, 255)));
        txt_inputCgst.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_inputCgstActionPerformed(evt);
            }
        });

        txt_outputCgst.setBackground(new java.awt.Color(52, 51, 52));
        txt_outputCgst.setForeground(new java.awt.Color(255, 255, 255));
        txt_outputCgst.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(255, 255, 255)));
        txt_outputCgst.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_outputCgstActionPerformed(evt);
            }
        });

        lbl_ledgerCrCode8.setBackground(new java.awt.Color(255, 255, 255));
        lbl_ledgerCrCode8.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        lbl_ledgerCrCode8.setForeground(new java.awt.Color(255, 255, 255));
        lbl_ledgerCrCode8.setText("SGST");

        txt_inputSgst.setBackground(new java.awt.Color(52, 51, 52));
        txt_inputSgst.setForeground(new java.awt.Color(255, 255, 255));
        txt_inputSgst.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(255, 255, 255)));
        txt_inputSgst.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_inputSgstActionPerformed(evt);
            }
        });

        txt_outputSgst.setBackground(new java.awt.Color(52, 51, 52));
        txt_outputSgst.setForeground(new java.awt.Color(255, 255, 255));
        txt_outputSgst.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(255, 255, 255)));
        txt_outputSgst.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_outputSgstActionPerformed(evt);
            }
        });

        lbl_ledgerCrCode9.setBackground(new java.awt.Color(255, 255, 255));
        lbl_ledgerCrCode9.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        lbl_ledgerCrCode9.setForeground(new java.awt.Color(255, 255, 255));
        lbl_ledgerCrCode9.setText("IGST");

        txt_inputIgst.setBackground(new java.awt.Color(52, 51, 52));
        txt_inputIgst.setForeground(new java.awt.Color(255, 255, 255));
        txt_inputIgst.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(255, 255, 255)));
        txt_inputIgst.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_inputIgstActionPerformed(evt);
            }
        });

        txt_outputIgst.setBackground(new java.awt.Color(52, 51, 52));
        txt_outputIgst.setForeground(new java.awt.Color(255, 255, 255));
        txt_outputIgst.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(255, 255, 255)));
        txt_outputIgst.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_outputIgstActionPerformed(evt);
            }
        });

        btn_createMaster.setBackground(new java.awt.Color(52, 51, 52));
        btn_createMaster.setForeground(new java.awt.Color(255, 255, 255));
        btn_createMaster.setText("Create Master");
        btn_createMaster.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_createMaster.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_createMasterActionPerformed(evt);
            }
        });

        btn_findMaster.setBackground(new java.awt.Color(52, 51, 52));
        btn_findMaster.setForeground(new java.awt.Color(255, 255, 255));
        btn_findMaster.setText("Find Master");
        btn_findMaster.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_findMaster.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_findMasterActionPerformed(evt);
            }
        });

        btn_updateMaster.setBackground(new java.awt.Color(52, 51, 52));
        btn_updateMaster.setForeground(new java.awt.Color(255, 255, 255));
        btn_updateMaster.setText("Update Master");
        btn_updateMaster.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_updateMaster.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_updateMasterActionPerformed(evt);
            }
        });

        btn_deleteMaster.setBackground(new java.awt.Color(52, 51, 52));
        btn_deleteMaster.setForeground(new java.awt.Color(255, 255, 255));
        btn_deleteMaster.setText("Delete Master");
        btn_deleteMaster.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_deleteMaster.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_deleteMasterActionPerformed(evt);
            }
        });

        btn_cancel.setBackground(new java.awt.Color(52, 51, 52));
        btn_cancel.setForeground(new java.awt.Color(255, 255, 255));
        btn_cancel.setText("Cancel");
        btn_cancel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_cancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_cancelActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(21, Short.MAX_VALUE)
                .addComponent(btn_createMaster)
                .addGap(18, 18, 18)
                .addComponent(btn_findMaster)
                .addGap(18, 18, 18)
                .addComponent(btn_updateMaster)
                .addGap(18, 18, 18)
                .addComponent(btn_deleteMaster)
                .addGap(18, 18, 18)
                .addComponent(btn_cancel)
                .addGap(19, 19, 19))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(111, 111, 111)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbl_ledgerCrCode4)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(lbl_input)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txt_input, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(lbl_output)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txt_output, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(lbl_GSTCatName)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txt_GstCatName, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(lbl_GSTCatCode)
                        .addGap(18, 18, 18)
                        .addComponent(txt_GstCatCode, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lbl_input1)
                                    .addComponent(lbl_output1))
                                .addGap(27, 27, 27)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txt_inputCgst)
                                    .addComponent(txt_outputCgst, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(81, 81, 81)
                                .addComponent(lbl_ledgerCrCode7)))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(27, 27, 27)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txt_inputSgst)
                                    .addComponent(txt_outputSgst, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(41, 41, 41)
                                .addComponent(lbl_ledgerCrCode8)))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(28, 28, 28)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txt_inputIgst)
                                    .addComponent(txt_outputIgst, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(46, 46, 46)
                                .addComponent(lbl_ledgerCrCode9)))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_GSTCatCode, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txt_GstCatCode, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_GSTCatName, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txt_GstCatName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_input, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txt_input, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl_output, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txt_output, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addComponent(lbl_ledgerCrCode4, javax.swing.GroupLayout.DEFAULT_SIZE, 26, Short.MAX_VALUE)
                .addGap(15, 15, 15)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_ledgerCrCode7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lbl_ledgerCrCode8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lbl_ledgerCrCode9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(15, 15, 15)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_input1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txt_inputCgst, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_inputSgst, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_inputIgst, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_output1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txt_outputCgst, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_outputSgst, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_outputIgst, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(58, 58, 58)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_updateMaster, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_findMaster, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_deleteMaster, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_createMaster, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_cancel, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(44, 44, 44))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void txt_GstCatCodeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_GstCatCodeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_GstCatCodeActionPerformed

    private void txt_GstCatNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_GstCatNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_GstCatNameActionPerformed

    private void txt_inputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_inputActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_inputActionPerformed

    private void txt_outputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_outputActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_outputActionPerformed

    private void txt_inputCgstActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_inputCgstActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_inputCgstActionPerformed

    private void txt_outputCgstActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_outputCgstActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_outputCgstActionPerformed

    private void txt_inputSgstActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_inputSgstActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_inputSgstActionPerformed

    private void txt_outputSgstActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_outputSgstActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_outputSgstActionPerformed

    private void txt_inputIgstActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_inputIgstActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_inputIgstActionPerformed

    private void txt_outputIgstActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_outputIgstActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_outputIgstActionPerformed

    private void btn_createMasterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_createMasterActionPerformed
        // TODO add your handling code here:
        String gstCateogryCode = txt_GstCatCode.getText();
        String gstCategoryName = txt_GstCatName.getText();
        String input = txt_input.getText();
        String output = txt_output.getText();
        String inputCGST = txt_inputCgst.getText();
        String inputSGST = txt_inputSgst.getText();
        String inputIGST = txt_inputIgst.getText();
        String outputCGST = txt_outputCgst.getText();
        String outputSGST = txt_outputSgst.getText();
        String outputIGST = txt_outputIgst.getText();
        
        try {
                DBConnection dbc = new DBConnection();
                Connection con = dbc.dbconnect();
                String queryCheck = "select * from gst_master where gstCategoryCode=?";
                PreparedStatement stmt = con.prepareStatement(queryCheck);
                stmt.setString(1, txt_GstCatCode.getText());
                final ResultSet rs = stmt.executeQuery();
                // if this ID already exists, we quit
                if(rs.next()) {
                    con.close();
                    JOptionPane.showMessageDialog(this, "User already exit");
                    return;
                }else{
                String str = "insert into gst_master values(?,?,?,?,?,?,?,?,?,?)";
                stmt = con.prepareStatement(str);
                stmt.setString(1, txt_GstCatCode.getText());
                stmt.setString(2, txt_GstCatName.getText());
                stmt.setString(3, txt_input.getText());
                stmt.setString(4, txt_output.getText());
                stmt.setString(5, txt_inputCgst.getText());
                stmt.setString(6, txt_inputSgst.getText());
                stmt.setString(7, txt_inputIgst.getText());
                stmt.setString(8, txt_outputCgst.getText());
                stmt.setString(9, txt_outputSgst.getText());
                stmt.setString(10, txt_outputIgst.getText());
                stmt.executeUpdate();
                    JOptionPane.showMessageDialog(this, "GST Master Generated Successfully.");
                }
                        txt_GstCatCode.setText("");
                        txt_GstCatName.setText("");
                        txt_input.setText("");
                        txt_output.setText("");
                        txt_inputCgst.setText("");
                        txt_inputSgst.setText("");
                        txt_inputIgst.setText("");
                        txt_outputCgst.setText("");
                        txt_outputSgst.setText("");
                        txt_outputIgst.setText("");
                } 
                catch (SQLException ex) {
                    Logger.getLogger(GstMaster.class.getName()).log(Level.SEVERE, null, ex);
                    JOptionPane.showMessageDialog(this, "GST Master Not generated!");
            }
    }//GEN-LAST:event_btn_createMasterActionPerformed

    private void btn_findMasterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_findMasterActionPerformed
        // TODO add your handling code here:
         String gstCateogryCode = txt_GstCatCode.getText();
        if(gstCateogryCode.equals("")){
            JOptionPane.showMessageDialog(rootPane, "Enter GST Category code to search the GST Master");
        }
        else{
        try {
            DBConnection dbc = new DBConnection();
            Connection con = dbc.dbconnect();
            String str = "select * from gst_master where gstCategoryCode=?";
            PreparedStatement stmt = con.prepareStatement(str);
            stmt.setString(1, txt_GstCatCode.getText());
            ResultSet rs =  stmt.executeQuery();
            if(rs.next()){
                txt_GstCatName.setText(rs.getString("gstCategoryName"));
                txt_input.setText(rs.getString("input"));
                txt_output.setText(rs.getString("output"));
                txt_inputCgst.setText(rs.getString("CGSTInput"));
                txt_inputSgst.setText(rs.getString("SGSTInput"));
                txt_inputIgst.setText(rs.getString("IGSTInput"));
                txt_outputCgst.setText(rs.getString("CGSTOutput"));
                txt_outputSgst.setText(rs.getString("SGSTOutput"));
                txt_outputIgst.setText(rs.getString("IGSTOutput"));
            }
            else{
                JOptionPane.showMessageDialog(this, "NO Data found!");
            }
        } catch (SQLException ex) {
            Logger.getLogger(GstMaster.class.getName()).log(Level.SEVERE, null, ex);
        }
        }
        
    }//GEN-LAST:event_btn_findMasterActionPerformed

    private void btn_updateMasterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_updateMasterActionPerformed
        // TODO add your handling code here:
        String gstCateogryCode = txt_GstCatCode.getText();
        String gstCategoryName = txt_GstCatName.getText();
        String input = txt_input.getText();
        String output = txt_output.getText();
        String inputCGST = txt_inputCgst.getText();
        String inputSGST = txt_inputSgst.getText();
        String inputIGST = txt_inputIgst.getText();
        String outputCGST = txt_outputCgst.getText();
        String outputSGST = txt_outputSgst.getText();
        String outputIGST = txt_outputIgst.getText();
        if(gstCateogryCode.equals("") || gstCategoryName.equals("") || input.equals("") || output.equals("") || inputCGST.equals("") || 
                inputSGST.equals("") || inputIGST.equals("") || outputCGST.equals("") || outputSGST.equals("") || outputIGST.equals(""))
        {
            JOptionPane.showMessageDialog(rootPane, "No Data Found");
        }
        else{
            try {
                DBConnection dbc = new DBConnection();
                Connection con = dbc.dbconnect();
                String str = "Update gst_master set gstCategoryName='"+txt_GstCatName.getText()+"',"
                        + "input='"+txt_input.getText()+"',"
                        + "output='"+txt_output.getText()+"',"
                        + "CGSTInput='"+txt_inputCgst.getText()+"',"
                        + "SGSTInput='"+txt_inputSgst.getText()+"',"
                        + "IGSTInput='"+txt_inputIgst.getText()+"',"
                        + "CGSTOutput='"+txt_outputCgst.getText()+"',"
                        + "SGSTOutput='"+txt_outputSgst.getText()+"',"
                        + "IGSTOutput='"+txt_outputIgst.getText()+"'where gstCategoryCode='"+txt_GstCatCode.getText()+"'";
                PreparedStatement stmt = con.prepareStatement(str);
                stmt.executeUpdate();
                JOptionPane.showMessageDialog(this, "Voucher updated successfully");
                        txt_GstCatCode.setText("");
                        txt_GstCatName.setText("");
                        txt_input.setText("");
                        txt_output.setText("");
                        txt_inputCgst.setText("");
                        txt_inputSgst.setText("");
                        txt_inputIgst.setText("");
                        txt_outputCgst.setText("");
                        txt_outputSgst.setText("");
                        txt_outputIgst.setText("");
                } catch (SQLException ex) {
                    Logger.getLogger(GstMaster.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
    }//GEN-LAST:event_btn_updateMasterActionPerformed

    private void btn_deleteMasterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_deleteMasterActionPerformed
        // TODO add your handling code here:
        String gstCateogryCode = txt_GstCatCode.getText();
        String gstCategoryName = txt_GstCatName.getText();
        String input = txt_input.getText();
        String output = txt_output.getText();
        String inputCGST = txt_inputCgst.getText();
        String inputSGST = txt_inputSgst.getText();
        String inputIGST = txt_inputIgst.getText();
        String outputCGST = txt_outputCgst.getText();
        String outputSGST = txt_outputSgst.getText();
        String outputIGST = txt_outputIgst.getText();
        if(gstCateogryCode.equals("") || gstCategoryName.equals("") || input.equals("") || output.equals("") || inputCGST.equals("") || 
                inputSGST.equals("") || inputIGST.equals("") || outputCGST.equals("") || outputSGST.equals("") || outputIGST.equals(""))
        {
            JOptionPane.showMessageDialog(rootPane, "No Data Found");
        }
        else{
                    try {
                            DBConnection dbc = new DBConnection();
                            Connection con = dbc.dbconnect();
                            String str = "Delete from gst_master where gstCategoryCode='"+txt_GstCatCode.getText()+"'";
                            PreparedStatement stmt = con.prepareStatement(str);
                            stmt.executeUpdate();
                            JOptionPane.showMessageDialog(this, "Voucher record deleted successfully");
                                txt_GstCatCode.setText("");
                                txt_GstCatName.setText("");
                                txt_input.setText("");
                                txt_output.setText("");
                                txt_inputCgst.setText("");
                                txt_inputSgst.setText("");
                                txt_inputIgst.setText("");
                                txt_outputCgst.setText("");
                                txt_outputSgst.setText("");
                                txt_outputIgst.setText("");
                            con.close();
                        } catch (SQLException ex) {
                            Logger.getLogger(GstMaster.class.getName()).log(Level.SEVERE, null, ex);
                        }
            }
    }//GEN-LAST:event_btn_deleteMasterActionPerformed

    private void btn_cancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_cancelActionPerformed
        // TODO add your handling code here:
        //        new AccountMaster().setVisible(true);
        dispose();
    }//GEN-LAST:event_btn_cancelActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GstMaster.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GstMaster.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GstMaster.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GstMaster.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GstMaster().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_cancel;
    private javax.swing.JButton btn_createMaster;
    private javax.swing.JButton btn_deleteMaster;
    private javax.swing.JButton btn_findMaster;
    private javax.swing.JButton btn_updateMaster;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lbl_GSTCatCode;
    private javax.swing.JLabel lbl_GSTCatName;
    private javax.swing.JLabel lbl_input;
    private javax.swing.JLabel lbl_input1;
    private javax.swing.JLabel lbl_ledgerCrCode4;
    private javax.swing.JLabel lbl_ledgerCrCode7;
    private javax.swing.JLabel lbl_ledgerCrCode8;
    private javax.swing.JLabel lbl_ledgerCrCode9;
    private javax.swing.JLabel lbl_output;
    private javax.swing.JLabel lbl_output1;
    private javax.swing.JTextField txt_GstCatCode;
    private javax.swing.JTextField txt_GstCatName;
    private javax.swing.JTextField txt_input;
    private javax.swing.JTextField txt_inputCgst;
    private javax.swing.JTextField txt_inputIgst;
    private javax.swing.JTextField txt_inputSgst;
    private javax.swing.JTextField txt_output;
    private javax.swing.JTextField txt_outputCgst;
    private javax.swing.JTextField txt_outputIgst;
    private javax.swing.JTextField txt_outputSgst;
    // End of variables declaration//GEN-END:variables
}
