/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.nibbannews;

import java.awt.List;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author Admin
 */
public class ManageEmployee extends javax.swing.JFrame {
   
   

    /**
     * Creates new form ManageEmployee
     */
    public ManageEmployee() {
        initComponents();
        setExtendedState(JFrame.MAXIMIZED_BOTH);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        txt_empid = new javax.swing.JTextField();
        txt_fullname = new javax.swing.JTextField();
        txt_age = new javax.swing.JTextField();
        txt_email = new javax.swing.JTextField();
        txt_phone = new javax.swing.JTextField();
        txt_password = new javax.swing.JTextField();
        btn_addEmployee = new javax.swing.JButton();
        btn_updateEmployee = new javax.swing.JButton();
        btn_deleteEmployee = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        btn_searchEmployee = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        cb_gender = new javax.swing.JComboBox<>();
        btb_clear = new javax.swing.JButton();
        cb_userRoll = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(52, 51, 52));

        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setIcon(new javax.swing.ImageIcon("C:\\Users\\Admin\\Downloads\\back-button.png")); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Employee Portal");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Employee ID:");
        jLabel2.setVerifyInputWhenFocusTarget(false);

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Full Name:");

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Age:");

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Gender:");

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Email ID:");

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Phone No:");

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Password:");

        txt_empid.setPreferredSize(new java.awt.Dimension(88, 20));

        txt_fullname.setPreferredSize(new java.awt.Dimension(88, 20));

        txt_age.setPreferredSize(new java.awt.Dimension(88, 20));

        txt_email.setPreferredSize(new java.awt.Dimension(88, 20));

        txt_phone.setPreferredSize(new java.awt.Dimension(88, 20));

        txt_password.setPreferredSize(new java.awt.Dimension(88, 20));

        btn_addEmployee.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        btn_addEmployee.setText("Add Employee");
        btn_addEmployee.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_addEmployeeActionPerformed(evt);
            }
        });

        btn_updateEmployee.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        btn_updateEmployee.setText("Update Employee");
        btn_updateEmployee.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_updateEmployeeActionPerformed(evt);
            }
        });

        btn_deleteEmployee.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        btn_deleteEmployee.setText("Delete Employee");
        btn_deleteEmployee.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_deleteEmployeeActionPerformed(evt);
            }
        });

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Emp ID", "Username", "Full Name", "Age", "Gender", "Email ID", "Phone No", "Password"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable1);

        btn_searchEmployee.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        btn_searchEmployee.setText("Search Employee");
        btn_searchEmployee.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_searchEmployeeActionPerformed(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("User roll:");

        cb_gender.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select", "Male", "Female", "Trans Gender" }));

        btb_clear.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        btb_clear.setText("Clear Form");
        btb_clear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btb_clearActionPerformed(evt);
            }
        });

        cb_userRoll.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select", "Admin", "Accountant", "IT", "Journalist", "Editor", "Sub-Edior", "Content Writer" }));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(629, 629, 629))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(229, 229, 229)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txt_empid, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_fullname, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cb_userRoll, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_age, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cb_gender, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_email, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_phone, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_password, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 751, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btn_addEmployee)
                        .addGap(62, 62, 62)
                        .addComponent(btn_searchEmployee)
                        .addGap(68, 68, 68)
                        .addComponent(btn_updateEmployee)
                        .addGap(69, 69, 69)
                        .addComponent(btn_deleteEmployee)
                        .addGap(75, 75, 75)
                        .addComponent(btb_clear)))
                .addContainerGap(260, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton1)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(48, 48, 48)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(20, 20, 20)
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(14, 14, 14)
                        .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(16, 16, 16)
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(14, 14, 14)
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(12, 12, 12)
                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(14, 14, 14)
                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(14, 14, 14)
                        .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(txt_empid, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(19, 19, 19)
                                .addComponent(txt_fullname, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(17, 17, 17)
                                .addComponent(cb_userRoll, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(13, 13, 13)
                                .addComponent(txt_age, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(13, 13, 13)
                                .addComponent(cb_gender, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(11, 11, 11)
                                .addComponent(txt_email, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(13, 13, 13)
                                .addComponent(txt_phone, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(13, 13, 13)
                                .addComponent(txt_password, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 355, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(49, 49, 49)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btn_addEmployee)
                        .addComponent(btn_searchEmployee))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btn_deleteEmployee)
                        .addComponent(btb_clear)
                        .addComponent(btn_updateEmployee)))
                .addContainerGap(118, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btn_addEmployeeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_addEmployeeActionPerformed
        // TODO add your handling code here:
        String empID = txt_empid.getText();
        String fullName = txt_fullname.getText();
        String userRoll = cb_userRoll.getSelectedItem().toString();
        String age = txt_age.getText();
        String gender = cb_gender.getSelectedItem().toString();
        String emailID = txt_email.getText();
        String phoneNo = txt_phone.getText();
        String pwd = txt_password.getText();
        if(empID.equals("") || fullName.equals("") || userRoll.equals("Select") || age.equals("") || gender.equals("Select") || emailID.equals("") || phoneNo.equals("") || pwd.equals("")){
            JOptionPane.showMessageDialog(rootPane, "All feilds are required");
        }
        else{
            try {
                DBConnection dbc = new DBConnection();
                Connection con = dbc.dbconnect();
                String queryCheck = "select * from employee where Emp_id=?";
                PreparedStatement stmt = con.prepareStatement(queryCheck);
                stmt.setString(1, txt_empid.getText());
                final ResultSet rs = stmt.executeQuery();
                // if this ID already exists, we quit
                if(rs.next()) {
                    con.close();
                    JOptionPane.showMessageDialog(this, "User already exit");
                    return;
                }else{
                String str = "insert into employee values(?,?,?,?,?,?,?,?)";
                stmt = con.prepareStatement(str);
                stmt.setString(1, txt_empid.getText());
    //            stmt.setString(2, txt_username.getText());
                stmt.setString(2, txt_fullname.getText());
                String userRoll_value = cb_userRoll.getSelectedItem().toString();
                stmt.setString(3, userRoll_value);
                stmt.setString(4, txt_age.getText());
                String gender_value = cb_gender.getSelectedItem().toString();
                stmt.setString(5, gender_value);
                stmt.setString(6, txt_email.getText());
                stmt.setString(7, txt_phone.getText());
                stmt.setString(8, txt_password.getText());
                stmt.executeUpdate();
                JOptionPane.showMessageDialog(this, "Employee Added Successfully");
                }
                txt_empid.setText("");
    //            txt_username.setText("");
                txt_fullname.setText("");
                cb_userRoll.setSelectedIndex(0);
                txt_age.setText("");
                cb_gender.setSelectedIndex(0);
                txt_email.setText("");
                txt_phone.setText("");
                txt_password.setText("");
                } 
                catch (SQLException ex) {
                    Logger.getLogger(ManageEmployee.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_btn_addEmployeeActionPerformed

    private void btn_searchEmployeeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_searchEmployeeActionPerformed
        // TODO add your handling code here:
        String empID = txt_empid.getText();
        if(empID.equals("")){
            JOptionPane.showMessageDialog(rootPane, "Enter Employee ID to search the employee");
        }
        else{
        try {
            DBConnection dbc = new DBConnection();
            Connection con = dbc.dbconnect();
            String str = "select * from employee where Emp_id=?";
            PreparedStatement stmt = con.prepareStatement(str);
            stmt.setString(1, txt_empid.getText());
            ResultSet rs =  stmt.executeQuery();
            if(rs.next()){
//                txt_username.setText(rs.getString("username"));
                txt_fullname.setText(rs.getString("full_name"));
                String userRoll_value = rs.getString("user_roll");
                cb_userRoll.addItem(userRoll_value);
                txt_age.setText(rs.getString("age"));
                String gender_value = rs.getString("gender");
                cb_gender.addItem(gender_value);
                txt_email.setText(rs.getString("email_id"));
                txt_phone.setText(rs.getString("phone_no"));
                txt_password.setText(rs.getString("password"));
            }
            else{
                JOptionPane.showMessageDialog(this, "NO employee found!");
            }
        } catch (SQLException ex) {
            Logger.getLogger(ManageEmployee.class.getName()).log(Level.SEVERE, null, ex);
        }
        }
    }//GEN-LAST:event_btn_searchEmployeeActionPerformed

    private void btb_clearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btb_clearActionPerformed
        // TODO add your handling code here:
            txt_empid.setText("");
//            txt_username.setText("");
            txt_fullname.setText("");
            cb_userRoll.setSelectedIndex(0);
            txt_age.setText("");
            cb_gender.setSelectedIndex(0);
            txt_email.setText("");
            txt_phone.setText("");
            txt_password.setText("");
    }//GEN-LAST:event_btb_clearActionPerformed

    private void btn_updateEmployeeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_updateEmployeeActionPerformed
        // TODO add your handling code here:
        String empID = txt_empid.getText();
        String fullName = txt_fullname.getText();
        String userRoll = cb_userRoll.getSelectedItem().toString();
        String age = txt_age.getText();
        String gender = cb_gender.getSelectedItem().toString();
        String emailID = txt_email.getText();
        String phoneNo = txt_phone.getText();
        String pwd = txt_password.getText();
        if(empID.equals("") || fullName.equals("") || userRoll.equals("Select") || age.equals("") || gender.equals("Select") || emailID.equals("") || phoneNo.equals("") || pwd.equals("")){
            JOptionPane.showMessageDialog(rootPane, "No input found");
        }
        else{
            try {
                DBConnection dbc = new DBConnection();
                Connection con = dbc.dbconnect();
                String str = "Update employee set full_name='"+txt_fullname.getText()+"',"
                        + "user_roll='"+cb_userRoll.getSelectedItem()+"',"
                        + "age='"+txt_age.getText()+"',"
                        + "gender='"+cb_gender.getSelectedItem()+"',"
                        + "email_id='"+txt_email.getText()+"',"
                        + "phone_no='"+txt_phone.getText()+"',"
                        + "password='"+txt_password.getText()+"'where Emp_id='"+txt_empid.getText()+"'";
                PreparedStatement stmt = con.prepareStatement(str);
                stmt.executeUpdate();
                JOptionPane.showMessageDialog(this, "Employee record updated successfully");
                txt_empid.setText("");
    //            txt_username.setText("");
                txt_fullname.setText("");
                cb_userRoll.setSelectedIndex(0);
                txt_age.setText("");
                cb_gender.setSelectedIndex(0);
                txt_email.setText("");
                txt_phone.setText("");
                txt_password.setText("");
                } catch (SQLException ex) {
                    Logger.getLogger(ManageEmployee.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
    }//GEN-LAST:event_btn_updateEmployeeActionPerformed

    private void btn_deleteEmployeeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_deleteEmployeeActionPerformed
        // TODO add your handling code here:
        String empID = txt_empid.getText();
        String fullName = txt_fullname.getText();
        String userRoll = cb_userRoll.getSelectedItem().toString();
        String age = txt_age.getText();
        String gender = cb_gender.getSelectedItem().toString();
        String emailID = txt_email.getText();
        String phoneNo = txt_phone.getText();
        String pwd = txt_password.getText();
        if(empID.equals("") || fullName.equals("") || userRoll.equals("Select") || age.equals("") || gender.equals("Select") || emailID.equals("") || phoneNo.equals("") || pwd.equals("")){
            JOptionPane.showMessageDialog(rootPane, "No input found");
        }
        else{
//        int response = JOptionPane.showConfirmDialog(this, "Do you really want to delete?", "Confirm", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);
//        if(response == 0){
//            txt_empid.setText("");
//            txt_fullname.setText("");
//            cb_userRoll.setSelectedIndex(0);
//            txt_age.setText("");
//            cb_gender.setSelectedIndex(0);
//            txt_email.setText("");
//            txt_phone.setText("");
//            txt_password.setText("");
        try {
            DBConnection dbc = new DBConnection();
            Connection con = dbc.dbconnect();
            String str = "Delete from employee where Emp_id='"+txt_empid.getText()+"'";
            PreparedStatement stmt = con.prepareStatement(str);
            stmt.executeUpdate();
            JOptionPane.showMessageDialog(this, "Employee record deleted successfully");
            txt_empid.setText("");
            txt_fullname.setText("");
            cb_userRoll.setSelectedIndex(0);
            txt_age.setText("");
            cb_gender.setSelectedIndex(0);
            txt_email.setText("");
            txt_phone.setText("");
            txt_password.setText("");
            con.close();
            } 
            catch (SQLException ex) {
                Logger.getLogger(ManageEmployee.class.getName()).log(Level.SEVERE, null, ex);
            }
         }
       
    }//GEN-LAST:event_btn_deleteEmployeeActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        Portals portals = new Portals();
        portals.setVisible(true);
        dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ManageEmployee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ManageEmployee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ManageEmployee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ManageEmployee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ManageEmployee().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btb_clear;
    private javax.swing.JButton btn_addEmployee;
    private javax.swing.JButton btn_deleteEmployee;
    private javax.swing.JButton btn_searchEmployee;
    private javax.swing.JButton btn_updateEmployee;
    private javax.swing.JComboBox<String> cb_gender;
    private javax.swing.JComboBox<String> cb_userRoll;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField txt_age;
    private javax.swing.JTextField txt_email;
    private javax.swing.JTextField txt_empid;
    private javax.swing.JTextField txt_fullname;
    private javax.swing.JTextField txt_password;
    private javax.swing.JTextField txt_phone;
    // End of variables declaration//GEN-END:variables
}
